import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from enrich import apply

M5 = {
"basic-tips-working-with-data": {
  "objectives": [
    "Structure a data range so Excel's data tools work correctly",
    "Explain why one row per record and one column per field matters",
    "Avoid the layout choices that break sorting and filtering",
    "Use Data Validation to prevent bad entries at the source",
  ],
  "opening": {
    "heading": "Excel's data tools assume a shape",
    "blocks": [
      {"type": "scenario",
       "role": "You inherit the supply log at Lakeside Medical Associates.",
       "text": "The sheet has a title in A1, two blank rows, merged headings, a blank row separating each month, and totals in the middle of the data. Sorting scrambles it, filtering catches only the first month, and a PivotTable refuses to build at all.",
       "task": "Learn the layout Excel's data tools expect, because every one of them assumes it."},
      {"type": "paragraph",
       "text": "Sorting, filtering, subtotals, tables, and PivotTables all assume the same structure: one header row, one record per row, one field per column, and no blank rows or columns inside the data. Meet that and every tool works. Break it and each tool fails in its own confusing way."},
      {"type": "table",
       "caption": "Layout rules that make the data tools work",
       "columns": ["Rule", "Why", "Common violation"],
       "rows": [
         ["One header row", "Tools read row 1 as field names", "A title above the headers, or two header rows"],
         ["One record per row", "Each row is treated as a unit when sorted", "One item's data split across two rows"],
         ["No blank rows inside the data", "A blank row is read as the end of the range", "Blank rows used as visual separators"],
         ["No merged cells", "Merging destroys the row and column grid", "Merged section headings"],
         ["Totals outside the data", "A total inside the range sorts along with the data", "A subtotal row in the middle of the records"],
         ["One type per column", "Mixed text and numbers break sorting and summing", "Notes typed into a numeric column"],
       ]},
      {"type": "tip",
       "text": "Put titles and notes on a separate sheet, or above a blank row that sits outside the range you select. Keep the data region itself clean — a rectangle with a header row and nothing else. Presentation belongs on the output sheet, not in the data."},
    ],
  },
  "checks": [{"explanation": "Conditional Formatting applies formatting automatically based on rules you define, so cells change appearance as their values change. It is dynamic — unlike manually applied formatting, which stays put.",
    "rationales": [
      "Data Validation restricts what can be entered into a cell. It prevents bad input rather than highlighting it after the fact.",
      "Sparklines are miniature charts drawn inside a single cell. They visualize a trend rather than highlighting cells by rule.",
      "Correct. Conditional Formatting applies formatting automatically according to rules you define.",
      "Cell Styles apply saved formatting when you choose them. They are applied manually and do not respond to values.",
    ]}],
},
"freezing-panes-view-options": {
  "objectives": [
    "Freeze rows and columns so headers stay visible while scrolling",
    "Split a window to view distant parts of a sheet at once",
    "Open a second window onto the same workbook",
    "Choose the right view tool for a given navigation problem",
  ],
  "opening": {
    "heading": "Losing the headers is a data-entry hazard",
    "blocks": [
      {"type": "scenario",
       "role": "You update quantities in a 900-row tracker at Lakeside Medical Associates.",
       "text": "At row 340 the headers are long gone. You are counting columns from the left to work out which is Reorder Level and which is Quantity on Hand. Eventually you miscount, and the entries go into the wrong column.",
       "task": "Keep the headers on screen, so every row is entered against a visible label."},
      {"type": "paragraph",
       "text": "Freeze Panes keeps chosen rows and columns fixed while the rest scrolls. The rule that catches everyone: Excel freezes everything above and to the left of the selected cell. To freeze row 1 and column A together, select B2 — not A1 — and then Freeze Panes."},
      {"type": "table",
       "caption": "Which view tool to use",
       "columns": ["You want", "Use", "How"],
       "rows": [
         ["Headers visible while scrolling", "Freeze Panes", "Select the cell below and right of what should stay, then freeze"],
         ["To compare row 5 with row 400", "Split", "View > Split — each pane scrolls independently"],
         ["Two sheets side by side", "New Window", "View > New Window, then Arrange All"],
         ["To hide detail temporarily", "Group", "Data > Group creates collapsible sections"],
       ]},
      {"type": "tip",
       "text": "View > New Window opens a second window onto the same workbook — not a copy. Edits in one appear instantly in the other, so you can watch a summary sheet update as you type into the data sheet. Arrange All tiles them side by side."},
    ],
  },
  "checks": [{"explanation": "Freezing keeps the top row fixed on screen while the rest of the sheet scrolls beneath it, so column headers stay visible at any row. It affects display only — nothing about the data changes.",
    "rationales": [
      "Freezing does not restrict editing. Preventing edits is sheet protection, a separate feature.",
      "The row can still be deleted. Freezing is purely a viewing setting.",
      "Correct. The row stays visible while the rest of the sheet scrolls.",
      "Freezing applies no formatting. Bold headers are a separate, and worthwhile, choice.",
    ]}],
},
"sorting-data": {
  "objectives": [
    "Sort by one column and by several columns in priority order",
    "Explain why selecting a single column before sorting corrupts data",
    "Use custom sort orders for non-alphabetical sequences",
    "Recognize when a sort has gone wrong and recover",
  ],
  "opening": {
    "heading": "The most destructive mistake in Excel",
    "blocks": [
      {"type": "scenario",
       "role": "You organize the supply list at Lakeside Medical Associates.",
       "text": "You click the Item Name column, select just that column, and sort A to Z. The names reorder. The quantities, prices, and vendors do not. Every row now pairs a name with another item's data, and there is no way to tell what belonged with what.",
       "task": "Sort in a way that keeps each record intact, and know how to recover when it goes wrong."},
      {"type": "paragraph",
       "text": "This is the error worth being genuinely careful about, because it is silent and often unrecoverable. Sorting one selected column reorders only that column. Every other column stays put, so the association between a name and its data is destroyed — and nothing on screen indicates anything is wrong."},
      {"type": "paragraph",
       "text": "The safe method is to click a single cell inside the data and use Data > Sort. Excel then detects the whole contiguous range and sorts complete rows, keeping records together. If a warning offers to 'Expand the selection,' always accept it — that dialog is Excel catching this exact mistake."},
      {"type": "callout", "variant": "warning",
       "text": "If you realize you have mis-sorted, press Ctrl+Z immediately and do nothing else first. Once you save and close, the original pairing is gone — there is no way to reconstruct which name belonged to which quantity. This is the strongest practical argument for storing working files in OneDrive, where version history can recover the previous state."},
      {"type": "tip",
       "text": "Add an index column numbered 1, 2, 3 before you start sorting a data set. Sorting by that column returns the sheet to its original order at any point, which turns an irreversible operation into a reversible one."},
    ],
  },
  "checks": [{"explanation": "An ascending sort runs smallest to largest — A to Z for text, earliest to latest for dates, lowest to highest for numbers.",
    "rationales": [
      "Descending is the reverse: Z to A, latest to earliest, highest to lowest.",
      "A custom sort defines a non-alphabetical order, such as Low, Medium, High. Useful, but not what A to Z means.",
      "Correct. Ascending sorts A to Z for text.",
      "A multi-level sort orders by several columns in priority. Each level is still ascending or descending.",
    ]}],
},
"filtering-data": {
  "objectives": [
    "Apply and clear filters on one or more columns",
    "Use text, number, and date filters for specific criteria",
    "Explain what filtering hides and what it does not remove",
    "Recognize when filtered rows are affecting your totals",
  ],
  "opening": {
    "heading": "Filtered rows are hidden, not gone",
    "blocks": [
      {"type": "scenario",
       "role": "You report on medical supply spending at Lakeside Medical Associates.",
       "text": "You filter the sheet to Medical Supplies and read the total at the bottom: $18,400. That figure is the total of every row in the sheet, including the office and cleaning supplies currently hidden. You report it as the medical supply spend, and it is wrong by about two-thirds.",
       "task": "Understand that filtering changes what you see, not what formulas calculate."},
      {"type": "paragraph",
       "text": "Filtering hides rows that do not match. The data is entirely intact and returns when the filter is cleared — which is what makes it safe. But SUM and AVERAGE include hidden rows, because they operate on the range, not on what happens to be visible."},
      {"type": "paragraph",
       "text": "=SUBTOTAL(109, E2:E900) is the fix: it sums only visible rows and updates as the filter changes. The 109 specifies sum-ignoring-hidden-rows. There is a parallel code for each function — 101 for average, 103 for count. Converting the range to an Excel Table gives you a Total Row that uses SUBTOTAL automatically."},
      {"type": "tip",
       "text": "When a filter is active, Excel's status bar reports the count of visible rows, and the filtered column's dropdown arrow shows a funnel icon. If a sheet looks like it is missing data, check for that funnel before concluding anything was deleted — an unnoticed filter is a very common false alarm."},
    ],
  },
  "checks": [{"explanation": "A filter temporarily hides rows that do not match your criteria. The data is untouched and returns the moment the filter is cleared — but be aware that ordinary SUM and AVERAGE still include the hidden rows.",
    "rationales": [
      "Nothing is deleted. Clearing the filter brings every row back, which is what makes filtering safe to use freely.",
      "Filtering and sorting are independent. A filter changes which rows are visible, not their order.",
      "Correct. Only rows matching the criteria remain visible; the rest are hidden but intact.",
      "That describes Conditional Formatting, which changes appearance. Filtering changes visibility.",
    ]}],
},
"groups-and-subtotals": {
  "objectives": [
    "Group rows and columns into collapsible outlines",
    "Apply automatic subtotals to a sorted data set",
    "Explain why data must be sorted before subtotalling",
    "Remove subtotals and return to a clean data range",
  ],
  "opening": {
    "heading": "Subtotals require a sort first",
    "blocks": [
      {"type": "scenario",
       "role": "You summarize spending by category at Lakeside Medical Associates.",
       "text": "You run Data > Subtotal on the supply sheet without sorting it first. Excel inserts a subtotal every time the category changes from one row to the next — producing forty-one subtotals across a sheet with four categories.",
       "task": "Sort by the grouping column first, so each category occupies one contiguous block."},
      {"type": "paragraph",
       "text": "The Subtotal command inserts a summary row whenever the value in your chosen column changes. It has no memory of categories it has already seen, so if the categories are scattered it dutifully subtotals each run. Sorting by that column first gathers each category into one block, and you get one subtotal per category."},
      {"type": "paragraph",
       "text": "Subtotals add an outline down the left edge with numbered buttons. Clicking 1 shows the grand total alone, 2 shows category subtotals, and 3 shows every row. That collapsibility is the real benefit — the same sheet serves both a manager wanting four numbers and an analyst wanting all 900 rows."},
      {"type": "callout", "variant": "info",
       "text": "Subtotals insert real rows into your data, which means the range is no longer a clean data set — sorting it again will scramble the subtotal rows in with the data. Remove them with Data > Subtotal > Remove All before doing anything else with the range. For repeated analysis, a PivotTable is the better tool, because it summarizes without altering the source at all."},
    ],
  },
  "checks": [{"explanation": "Subtotal inserts summary rows into a sorted data set, calculating a sum, average, count, or similar for each group, and adds a collapsible outline so you can move between summary and detail.",
    "rationales": [
      "Subtotal does not sort — which is exactly the trap. You must sort by the grouping column yourself first, or you get a subtotal at every change of value.",
      "Removing duplicates is a separate command on the Data tab.",
      "Correct. It calculates summary values for each group and adds an outline for collapsing detail.",
      "Converting to a Table is Insert > Table, a different feature. Subtotal inserts summary rows into the existing range.",
    ]}],
},
"conditional-formatting": {
  "objectives": [
    "Apply highlight rules, data bars, color scales, and icon sets",
    "Write a formula-based conditional formatting rule",
    "Manage rule precedence when several rules apply",
    "Use conditional formatting to surface data problems",
  ],
  "opening": {
    "heading": "Formatting that keeps itself up to date",
    "blocks": [
      {"type": "scenario",
       "role": "You monitor stock levels at Lakeside Medical Associates.",
       "text": "You highlight the below-reorder items in red by hand. A week later the quantities have all changed, but the red highlights have not — they are still marking the items that were low last week. The colour is now actively misleading.",
       "task": "Make the formatting a rule about the data, so it can never go stale."},
      {"type": "paragraph",
       "text": "Conditional formatting applies formatting according to a rule evaluated continuously. Set 'highlight cells less than the value in the reorder column' and the highlights follow the data as it changes, with no maintenance at all."},
      {"type": "table",
       "caption": "Rule types and what each is for",
       "columns": ["Type", "Shows", "Best for"],
       "rows": [
         ["Highlight Cells Rules", "Formatting when a condition is met", "Flagging exceptions — below reorder, over budget"],
         ["Top/Bottom Rules", "The highest or lowest values", "Finding the ten largest expenses"],
         ["Data Bars", "An in-cell bar proportional to the value", "Comparing magnitudes across a column at a glance"],
         ["Color Scales", "A color gradient across the range", "Seeing the distribution — where the highs and lows cluster"],
         ["Icon Sets", "Arrows, flags, or traffic lights", "Status at a glance, with a legend"],
         ["Formula rule", "Formatting driven by any formula", "Highlighting a whole row based on one cell's value"],
       ]},
      {"type": "worked-example",
       "title": "Highlighting an entire row when stock is low",
       "task": "Make the whole row turn amber when Quantity on Hand falls below Reorder Level, so a scan down the sheet shows what needs ordering.",
       "steps": [
         {"move": "Select the full data range, A2:F900, starting from the top-left data cell.",
          "why": "A formula rule is evaluated relative to the active cell in your selection, so where the selection starts determines how the formula is interpreted. Selecting from A2 means the rule is written as though it lives in A2."},
         {"move": "New Rule > Use a formula to determine which cells to format, and enter =$D2<$E2.",
          "why": "The dollar signs before D and E lock the columns, so every cell in the row tests the same two columns. Leaving the row number relative lets it advance down the sheet. This mixed reference is precisely what makes whole-row formatting work."},
         {"move": "Set the format to an amber fill, and confirm.",
          "why": "Amber rather than red leaves red available for something genuinely urgent, such as out of stock. Reserving intensity for severity keeps the sheet readable."},
         {"move": "Add a status column reading 'Reorder' driven by the same condition.",
          "why": "Color alone fails in greyscale printing and for colorblind readers, and it cannot be filtered on. A text column can be filtered, sorted, and counted — the color becomes a helpful accent rather than the only signal."},
       ],
       "result": "Rows that flag themselves as stock falls, with a text status that also works on paper and can be filtered.",
       "takeaway": "Lock the column, leave the row relative, and always pair color with something non-visual."},
    ],
  },
  "checks": [{"explanation": "Color Scales apply a gradient across the range, so each cell's color reflects its value relative to the others. It is the fastest way to see how values are distributed.",
    "rationales": [
      "Highlight Cells Rules apply one fixed format when a condition is met, rather than a gradient across values.",
      "Icon Sets place a symbol in the cell — an arrow or traffic light — instead of shading it.",
      "Data Bars draw a bar inside each cell proportional to its value. Close, but the bar is a shape rather than a color gradient.",
      "Correct. Color Scales shade cells along a gradient according to their values.",
    ]}],
},
}

M6 = {
"working-with-tables": {
  "objectives": [
    "Convert a range to an Excel Table and explain what changes",
    "Use structured references in formulas",
    "Add a total row that respects filtering",
    "Judge when a Table helps and when a plain range is fine",
  ],
  "opening": {
    "heading": "A Table knows where its data ends",
    "blocks": [
      {"type": "scenario",
       "role": "You maintain the supply tracker at Lakeside Medical Associates.",
       "text": "Your chart and PivotTable are built on A1:F200. Twelve new rows are added at row 201. The chart does not include them, the PivotTable does not include them, and both look completely normal. Nobody notices for a month.",
       "task": "Use a Table so the range grows with the data and everything built on it follows."},
      {"type": "paragraph",
       "text": "Insert > Table converts a range into a named object that tracks its own extent. Type into the row below and the Table absorbs it — and so does every chart, PivotTable, and formula referencing the Table. This is the single feature that prevents the silent staleness above."},
      {"type": "paragraph",
       "text": "Tables also change how formulas read. =SUM(Orders[Cost]) says what it means, where =SUM(E2:E200) requires you to go and look. Structured references make formulas self-documenting, and they cannot drift out of alignment with the data the way fixed ranges do."},
      {"type": "table",
       "caption": "What converting to a Table gives you",
       "columns": ["Feature", "Effect"],
       "rows": [
         ["Auto-expanding range", "New rows and columns are included automatically everywhere"],
         ["Structured references", "=SUM(Orders[Cost]) instead of =SUM(E2:E200)"],
         ["Filter buttons", "Added to every header automatically"],
         ["Total row", "Uses SUBTOTAL, so it respects filtering"],
         ["Banded rows", "Readability that survives sorting and inserting"],
         ["Formula fill", "A formula entered in one cell fills the whole column"],
       ]},
      {"type": "tip",
       "text": "Name the Table as soon as you create it — Table Design > Table Name. 'Orders' reads far better in formulas than 'Table1', and in a workbook with several tables the default names become impossible to keep straight."},
    ],
  },
  "checks": [{"explanation": "A Table tracks its own extent, so rows added at the bottom are absorbed automatically — and every chart, PivotTable, and formula referencing the Table picks them up without being updated.",
    "rationales": [
      "Tables do not lock cells. Protection is a separate feature on the Review tab.",
      "Correct. The Table expands to include new rows, and everything referencing it follows.",
      "Formulas stay formulas. Tables actually make formulas more readable through structured references.",
      "Removing duplicates is a separate command on the Data tab. Converting to a Table does not alter your data.",
    ]}],
},
"charts": {
  "objectives": [
    "Choose a chart type that matches the question the data answers",
    "Create and format a chart with clear titles and labels",
    "Explain how axis choices can mislead a reader",
    "Decide when a table communicates better than a chart",
  ],
  "opening": {
    "heading": "The chart type is a claim about the data",
    "blocks": [
      {"type": "scenario",
       "role": "You present supply spending to the board at Lakeside Medical Associates.",
       "text": "You build a pie chart with eleven slices to show spending by category. Four slices are under 3% and their labels overlap into an unreadable tangle. A board member asks which of two similar slices is larger, and nobody can tell by looking.",
       "task": "Match the chart to the question, and recognize when a table would serve better."},
      {"type": "paragraph",
       "text": "Human perception judges length far more accurately than angle or area. That single fact explains most chart guidance: bar and column charts are read accurately, pie charts poorly. A pie chart works only for parts of one whole, with few enough slices that the comparison is obvious — five or fewer is the usual advice."},
      {"type": "table",
       "caption": "Choosing a chart type",
       "columns": ["The question", "Chart", "Why"],
       "rows": [
         ["How did this change over time?", "Line", "A continuous line is read as continuity"],
         ["How do these categories compare?", "Column or bar", "Length is judged accurately"],
         ["What share is each part of the whole?", "Pie", "Only for parts of one whole, five or fewer slices"],
         ["Are these two measures related?", "Scatter", "Shows the relationship directly"],
         ["How does this distribute?", "Histogram", "Shows shape and spread"],
         ["Exact values matter more than shape", "A table", "Charts show patterns; tables give precision"],
       ]},
      {"type": "callout", "variant": "warning",
       "text": "On a column or bar chart, always start the value axis at zero. Readers compare bar lengths, so truncating the axis makes a 3% difference look like a doubling. Excel sometimes chooses a non-zero start automatically, which means a misleading chart can be produced entirely by accident — check the axis before you present it."},
      {"type": "tip",
       "text": "Title the chart with the finding, not the subject. 'Medical supply spending rose 18% in Q3' does the interpretive work for the reader. 'Supply Spending by Quarter' leaves them to work it out, and some will reach the wrong conclusion."},
    ],
  },
  "checks": [{"explanation": "A pie chart shows parts of a single whole. Keep it to five or fewer slices — beyond that, differences in angle become hard to judge and a bar chart communicates far better.",
    "rationales": [
      "Bar charts compare values across categories, which readers judge accurately — but the bars do not inherently represent shares of a whole.",
      "Line charts show change over a continuous variable, usually time.",
      "Correct. Pie charts show each category's share of a single total.",
      "Area charts show change over time with the area filled beneath. They emphasize magnitude over time rather than composition at a moment.",
    ]}],
},
"pivot-tables": {
  "objectives": [
    "Build a PivotTable from a clean data range",
    "Arrange fields across Rows, Columns, Values, and Filters",
    "Change how values are summarized",
    "Refresh a PivotTable when the source data changes",
  ],
  "opening": {
    "heading": "Answering four questions in three minutes",
    "blocks": [
      {"type": "scenario",
       "role": "You are asked for a spending breakdown at Lakeside Medical Associates.",
       "text": "Your supervisor asks: what did we spend per department last month, what are the top categories, which vendors got the most, and how does May compare with April? Answered with formulas and manual summary tables, that is most of an afternoon. Answered with one PivotTable, it is about three minutes.",
       "task": "Learn to summarize a large data set by rearranging fields rather than writing formulas."},
      {"type": "paragraph",
       "text": "A PivotTable summarizes a data set by whatever fields you drag into it, without altering the source in any way. Drag Department to Rows and Amount to Values and you have spending per department. Drag Month to Columns as well and you have a full cross-tab. Each rearrangement is a new question answered, and the underlying data is never touched."},
      {"type": "table",
       "caption": "The four areas",
       "columns": ["Area", "Field goes here to", "Example"],
       "rows": [
         ["Rows", "Become the row labels", "Department, one per row"],
         ["Columns", "Become the column headings", "Month, one per column"],
         ["Values", "Be summarized — summed, counted, averaged", "Amount, summed"],
         ["Filters", "Filter the whole table", "Year, to show one year at a time"],
       ]},
      {"type": "callout", "variant": "warning",
       "text": "PivotTables do not update automatically when the source data changes. You must click Refresh on the PivotTable Analyze tab, and forgetting is one of the most common ways a stale figure reaches a report. Building the PivotTable on an Excel Table rather than a fixed range at least ensures new rows are included when you do refresh."},
      {"type": "tip",
       "text": "If Excel summarizes a numeric column with Count instead of Sum, that column contains text somewhere — often a stray note or a number stored as text. The PivotTable is telling you about a data quality problem worth fixing at the source."},
    ],
  },
  "checks": [{"explanation": "A PivotTable summarizes and reorganizes a large data set — totalling, counting, and cross-tabulating by whatever fields you choose — without altering the source data at all. Rearranging fields answers a new question in seconds.",
    "rationales": [
      "Charts are created from Insert > Chart. A PivotChart can be built on a PivotTable, but summarizing is what the PivotTable itself does.",
      "Conditional Formatting is a separate feature and works on ranges rather than being a PivotTable function.",
      "Correct. It summarizes and reorganizes large data sets while leaving the source data untouched.",
      "PivotTables do not repair formulas. Error checking is under the Formulas tab.",
    ]}],
},
}

M7 = {
"doing-more-with-pivottables": {
  "objectives": [
    "Add slicers and timelines as visual filters",
    "Group dates and numeric values into meaningful bands",
    "Change value calculations to show percentages and running totals",
    "Connect one slicer to several PivotTables",
  ],
  "opening": {
    "heading": "Making a PivotTable usable by someone else",
    "blocks": [
      {"type": "scenario",
       "role": "You build the spending dashboard at Lakeside Medical Associates.",
       "text": "The practice manager needs to look at one department at a time. Explaining the PivotTable field list means explaining Rows, Columns, Values, and Filters. Adding a slicer means saying 'click the department you want.'",
       "task": "Add controls that let a non-Excel user explore the data without instruction."},
      {"type": "paragraph",
       "text": "A slicer is a filter with buttons. It does exactly what the Filters area does, but visibly — and crucially, it shows the current filter state, so nobody misreads a filtered table as the full picture. That failure mode is common enough with the Filters dropdown to justify slicers on its own."},
      {"type": "paragraph",
       "text": "A timeline is the equivalent for dates: a slider for choosing months, quarters, or years. Both can be connected to several PivotTables at once through Report Connections, so one click filters an entire dashboard consistently."},
      {"type": "tip",
       "text": "Show Values As (right-click a value > Show Values As) reframes numbers without any formula work: % of Grand Total, % of Parent Row, Running Total, or Difference From the previous period. 'Medical supplies are 46% of spending' often lands better than the raw dollar figure."},
      {"type": "callout", "variant": "info",
       "text": "Right-click a date field and choose Group to band dates by month, quarter, or year; the same command bands numbers into ranges. This is how a thousand individual transaction dates become a readable twelve-row monthly summary."},
    ],
  },
  "checks": [{"explanation": "A slicer is a visual filter: clickable buttons for each value in a field. Its advantage over the Filters dropdown is that the current filter state is always visible, so nobody mistakes a filtered table for the whole data set.",
    "rationales": [
      "Slicers filter a PivotTable. They never split it into separate tables.",
      "Nothing is deleted. Slicers filter what is displayed, leaving the source data untouched.",
      "Correct. A slicer provides visible, clickable filter buttons, with the current selection always on screen.",
      "Converting a PivotTable to a range is a separate operation. A slicer only filters.",
    ]}],
},
"what-if-analysis": {
  "objectives": [
    "Use Goal Seek to find the input needed for a target result",
    "Compare alternatives with Scenario Manager",
    "Use a Data Table to see results across many input values",
    "Explain what What-If tools can and cannot tell you",
  ],
  "opening": {
    "heading": "Working backwards from the answer you need",
    "blocks": [
      {"type": "scenario",
       "role": "You plan next year's supply budget at Lakeside Medical Associates.",
       "text": "The budget must come in at $85,000. Current projections say $92,400. The question is not what the total is — it is how much the per-visit supply cost would have to fall to reach the target. Guessing and re-checking is slow and imprecise.",
       "task": "Let Excel solve for the input value that produces the result you need."},
      {"type": "paragraph",
       "text": "Goal Seek (Data > What-If Analysis > Goal Seek) reverses a calculation. You name the formula cell, the result you want, and the input cell to vary. Excel adjusts that input until the formula produces the target. It answers 'what would this need to be?' rather than 'what is this?'"},
      {"type": "table",
       "caption": "The three What-If tools",
       "columns": ["Tool", "Answers", "Varies"],
       "rows": [
         ["Goal Seek", "What input gives me this exact result?", "One input"],
         ["Data Table", "What happens across a range of inputs?", "One or two inputs, many values"],
         ["Scenario Manager", "How do named alternatives compare?", "Several inputs, saved as named sets"],
       ]},
      {"type": "callout", "variant": "warning",
       "text": "Goal Seek finds the arithmetic answer, not the achievable one. It may report that the per-visit supply cost needs to fall 31%, which is a real number and possibly an impossible operational target. The tool tells you what the model requires; whether that is attainable is a judgment it cannot make. Always state the required change to a decision-maker rather than presenting it as a plan."},
    ],
  },
  "checks": [{"explanation": "Goal Seek works backwards from a target: you specify the result you want and which input may change, and Excel finds the input value that produces it.",
    "rationales": [
      "Scenario Manager compares named sets of input values. It shows how alternatives differ rather than solving for a target.",
      "A Data Table shows results across a range of input values in a grid. It surveys outcomes rather than finding one specific input.",
      "Solver handles complex problems with multiple variables and constraints. It is the heavier tool; Goal Seek is the right one for a single input and a single target.",
      "Correct. Goal Seek finds the input value needed to reach a specified result.",
    ]}],
},
"reference-styles": {
  "objectives": [
    "Explain the difference between A1 and R1C1 reference styles",
    "Switch between reference styles in Excel Options",
    "Read an R1C1 formula and recognize relative offsets",
    "Recognize when R1C1 is genuinely useful",
  ],
  "opening": {
    "heading": "The same cell, described two ways",
    "blocks": [
      {"type": "scenario",
       "role": "You audit an inherited workbook at Lakeside Medical Associates.",
       "text": "You open a colleague's file and the column headers are numbers instead of letters. Formulas read =RC[-1]*R1C6. Nothing is broken — the workbook is simply using the other reference style, and R1C1 is not something most people ever see.",
       "task": "Recognize R1C1 notation, know how to switch it off, and understand why it exists."},
      {"type": "paragraph",
       "text": "A1 style names a cell by column letter and row number. R1C1 style names it by row and column number, so row 3 column 2 is R3C2 — the same cell A1 style calls B3. Both describe an identical grid; only the notation differs."},
      {"type": "paragraph",
       "text": "R1C1's real utility is that it makes relative references explicit. In R1C1, brackets mean an offset from the current cell: RC[-1] is 'the cell one column to my left,' whatever row it is in. Copy that formula anywhere and it still reads RC[-1] — which makes it obvious that every cell in a column holds the same logic, something A1 style hides behind changing addresses."},
      {"type": "tip",
       "text": "To switch, go to File > Options > Formulas and check or uncheck 'R1C1 reference style.' It is a per-application setting rather than a property of the file, so a workbook that looks wrong to you looks normal to whoever created it."},
    ],
  },
  "checks": [{"explanation": "R1C1 style names the row first and the column second, so row 3 column 2 is R3C2 — the cell that A1 style calls B3.",
    "rationales": [
      "B3 is the A1-style name for the same cell. The question asks for the R1C1 form.",
      "This reverses the order. R1C1 style always puts the row before the column, which is what the name itself indicates.",
      "Correct. R3C2 means row 3, column 2.",
      "This mixes the two notations and is not valid in either style.",
    ]}],
},
}

apply("lib/content/ms-office/excel/module5Lessons.ts", M5)
apply("lib/content/ms-office/excel/module6Lessons.ts", M6)
apply("lib/content/ms-office/excel/module7Lessons.ts", M7)
