import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from enrich import apply

M1 = {
"getting-started-with-excel": {
  "objectives": [
    "Identify the Ribbon, formula bar, Name Box, and status bar and say what each does",
    "Describe a cell address and how rows and columns are labeled",
    "Read the status bar's automatic sum, average, and count",
    "Move around a large worksheet efficiently with keyboard navigation",
  ],
  "opening": {
    "heading": "A spreadsheet is a grid of addresses",
    "blocks": [
      {"type": "scenario",
       "role": "You are taking over supply tracking at Lakeside Medical Associates.",
       "text": "Your predecessor left a workbook with four sheets and about 900 rows. Your supervisor asks a simple question: what did we spend on medical supplies last quarter? You can see all the numbers. You just have no way to make the file answer the question.",
       "task": "Learn how a worksheet is addressed and navigated, because every Excel skill after this depends on referring to cells precisely."},
      {"type": "paragraph",
       "text": "Excel's power rests on one idea: every cell has an address. Columns are lettered, rows are numbered, and their intersection names the cell — C7 is column C, row 7. Because each cell has a stable address, a formula can refer to it, and when the value at that address changes, everything referring to it recalculates. That is the whole basis of a spreadsheet."},
      {"type": "paragraph",
       "text": "The formula bar is the other thing to understand early. A cell shows you a result; the formula bar shows you what is actually in it. A cell displaying 1,240 might contain the number 1240 or the formula =SUM(C2:C15). Those are very different things, and only the formula bar tells you which. When a spreadsheet behaves unexpectedly, clicking a cell and reading the formula bar is nearly always the first diagnostic step."},
      {"type": "key-terms",
       "terms": [
         {"term": "Cell reference", "definition": "A cell's address, formed from its column letter and row number — C7. Formulas use references rather than values so they update when the data changes."},
         {"term": "Range", "definition": "A block of cells written with a colon. C2:C15 means every cell from C2 through C15."},
         {"term": "Formula bar", "definition": "The bar above the grid showing the actual contents of the selected cell, as opposed to its displayed result."},
         {"term": "Name Box", "definition": "The box left of the formula bar showing the selected cell's address. Type an address into it to jump straight there."},
         {"term": "Worksheet vs workbook", "definition": "A workbook is the file. A worksheet is one tab inside it. One workbook can hold many worksheets."},
       ]},
      {"type": "table",
       "caption": "Navigation worth learning on day one",
       "columns": ["Keys", "Does", "Why it matters"],
       "rows": [
         ["Ctrl + Arrow", "Jumps to the edge of the current block of data", "Reaches the end of 900 rows instantly"],
         ["Ctrl + Home", "Returns to A1", "Gets you back from anywhere"],
         ["Ctrl + End", "Jumps to the last used cell", "Shows the true extent of a sheet, including stray data"],
         ["Ctrl + Shift + Arrow", "Selects to the edge of the block", "Selects a whole column of data without dragging"],
         ["F2", "Edits the active cell in place", "Faster than double-clicking, and shows the formula"],
       ]},
      {"type": "tip",
       "text": "Select several numbers and look at the bottom-right of the status bar: Excel is already showing their sum, average, and count. For a quick total you never need a formula at all. Right-click the status bar to choose which statistics appear there."},
    ],
  },
  "checks": [{"explanation": "The Ribbon holds Excel's commands, grouped into tabs by task — Home for formatting, Formulas for functions, Data for sorting and filtering. The formula bar and status bar display information about your data rather than housing commands.",
    "rationales": [
      "The status bar reports information — the sum of your selection, the zoom level, the current mode. It displays rather than commands.",
      "The formula bar shows and edits the contents of the active cell. It is essential, but it is not where commands live.",
      "Correct. The Ribbon organizes Excel's commands into task-based tabs.",
      "The Quick Access Toolbar holds a few shortcuts you choose. It is a convenience layer over the Ribbon, not the source of commands.",
    ]}],
},
"understanding-onedrive-for-excel": {
  "objectives": [
    "Save a workbook to OneDrive and open it from another device",
    "Explain what AutoSave requires and why it may be greyed out",
    "Use version history to recover an earlier state of a workbook",
    "Judge what data may and may not go into a personal cloud account",
  ],
  "opening": {
    "heading": "Version history is the feature worth the move",
    "blocks": [
      {"type": "scenario",
       "role": "You maintain the supply budget at Lakeside Medical Associates.",
       "text": "You sort a 900-row sheet, but you select only one column instead of the whole range. Every name is now attached to the wrong number and you cannot tell which row was which. You saved ten minutes ago. Ctrl+Z has already been exhausted.",
       "task": "Understand what cloud storage gives you beyond access from anywhere — specifically, the ability to go back."},
      {"type": "paragraph",
       "text": "Saving to OneDrive puts the workbook on Microsoft's servers so it follows you between devices. That much matches Word. What matters more in Excel is version history: OneDrive keeps previous versions, and File > Info > Version History lets you open or restore any of them."},
      {"type": "paragraph",
       "text": "Excel damage is often silent. A mis-sorted column, a formula overwritten with a typed number, a deleted row — none of these announce themselves, and you may not notice for days, long past what undo can reach. Version history is the only realistic recovery, and it exists only for cloud-stored files."},
      {"type": "callout", "variant": "warning",
       "text": "AutoSave changes a habit you may rely on. With AutoSave on, every change is written immediately — there is no 'close without saving' to abandon an experiment. Before trying something drastic on a live workbook, use File > Save a Copy first and experiment on the copy."},
      {"type": "callout", "variant": "warning",
       "text": "A spreadsheet holding patient names, dates of birth, or visit details is protected health information. It belongs only in systems your employer has assessed and covered by a business associate agreement — never in a personal OneDrive account. If you are unsure whether a workbook qualifies, ask before you save it."},
    ],
  },
  "checks": [{"explanation": "Saving to OneDrive stores the workbook on Microsoft's servers and syncs it to any device you sign in on. It is also the prerequisite for AutoSave, co-authoring, and version history.",
    "rationales": [
      "AutoRecover keeps temporary local copies to survive a crash. It protects against Excel closing unexpectedly, not against being at a different machine.",
      "Correct. The workbook lives in the cloud and syncs to any device you sign in on, which also enables version history and co-authoring.",
      "Leaving Excel running has no effect on where the file is stored or who can reach it.",
      "The Quick Access Toolbar holds command shortcuts. It has nothing to do with file storage or access.",
    ]}],
},
"creating-and-opening-workbooks": {
  "objectives": [
    "Create workbooks from blank files and from templates",
    "Open, pin, and manage recent workbooks",
    "Recognize the risks of opening workbooks from outside the practice",
    "Explain what CSV files lose compared with .xlsx",
  ],
  "opening": {
    "heading": "Where a workbook comes from is a security question",
    "blocks": [
      {"type": "scenario",
       "role": "You process vendor invoices at Lakeside Medical Associates.",
       "text": "A supplier emails a price list as an .xlsm file. Excel opens it in Protected View with a yellow bar offering to enable content. Clicking that button on a file from outside the practice is one of the most common ways an organization gets compromised.",
       "task": "Know what Protected View is protecting you from, and what the different file types mean."},
      {"type": "paragraph",
       "text": "Protected View opens files from email, the internet, or unsafe locations in a read-only sandbox where macros and external links cannot run. The yellow bar asking you to enable editing or enable content is a genuine decision point, not a formality. Enable editing on a file you were expecting from a known sender; be far more cautious about enabling content, which permits macros to execute."},
      {"type": "table",
       "caption": "Excel file types",
       "columns": ["Extension", "What it is", "Note"],
       "rows": [
         [".xlsx", "The standard workbook format", "Cannot contain macros, which makes it the safer default"],
         [".xlsm", "A macro-enabled workbook", "Can run code. Only enable content from a source you trust"],
         [".csv", "Plain comma-separated text", "Holds one sheet of values only — no formulas, formatting, or multiple tabs"],
         [".xltx", "A template", "Opening one creates a new workbook and leaves the template intact"],
         [".xls", "The pre-2007 format", "Limited to 65,536 rows; convert unless you must return it"],
       ]},
      {"type": "callout", "variant": "warning",
       "text": "Saving an .xlsx as .csv discards everything except the values on the current sheet — formulas become their results, formatting disappears, and other sheets are simply not saved. Excel warns you, and the warning is worth reading. CSV is an exchange format for moving data between systems, not a format to keep your work in."},
    ],
  },
  "checks": [{"explanation": "A template is a pre-built starting point holding layout, formatting, and often formulas. Opening one creates a new workbook from it, leaving the template itself unchanged so it can be reused.",
    "rationales": [
      "Templates are fully editable. You are thinking of workbook protection, which is a separate feature under the Review tab.",
      "Chart formatting can be saved as a chart template, but an Excel template is a whole workbook rather than a chart style.",
      "Correct. A template is a pre-formatted workbook used as a starting point, and opening it produces a new copy.",
      "A template can contain formulas, data, formatting, and charts. There is no restriction to formulas alone.",
    ]}],
},
"saving-exporting-and-sharing": {
  "objectives": [
    "Choose a save format that matches how the workbook will be used",
    "Export a worksheet to PDF with sensible page setup",
    "Share a workbook by link with appropriate permissions",
    "Explain what a recipient can still see in a shared workbook",
  ],
  "opening": {
    "heading": "Sending a workbook sends more than you can see",
    "blocks": [
      {"type": "scenario",
       "role": "You report supply spending to the practice manager at Lakeside Medical Associates.",
       "text": "You email the quarterly summary as an .xlsx. It also contains a hidden sheet with staff salary assumptions, a filtered-out set of rows, and the vendor's confidential pricing. All of it travels with the file, and the recipient can unhide it in two clicks.",
       "task": "Understand what actually leaves with a workbook, and choose a format that shares only what you intend."},
      {"type": "paragraph",
       "text": "A workbook carries everything: hidden sheets, hidden rows and columns, filtered-out data, comments, defined names, cell formulas revealing your method, and file metadata naming the author. Hiding is a display setting, not a security control — hidden data is fully present in the file."},
      {"type": "paragraph",
       "text": "This is the practical case for exporting to PDF. A PDF contains only what was visible when you exported it, and cannot be unhidden or reverse-engineered. Send the PDF when the recipient needs the numbers; send the workbook only when they genuinely need to work with the data."},
      {"type": "worked-example",
       "title": "Sending a quarterly summary safely",
       "task": "Share the supply spending summary with the practice manager without exposing hidden sheets, source pricing, or underlying formulas.",
       "steps": [
         {"move": "Run File > Info > Check for Issues > Inspect Document.",
          "why": "The Document Inspector reports hidden worksheets, hidden rows and columns, comments, and personal metadata. It surfaces things you have genuinely forgotten about — which is exactly the category of information that causes problems."},
         {"move": "Decide what the recipient actually needs: numbers, or data to work with.",
          "why": "This determines the format, and it is a decision most people skip. A manager reading a summary needs a PDF. An analyst continuing the work needs the workbook. Sending the workbook by default is how source pricing reaches people who should not have it."},
         {"move": "For numbers only, set the print area and export with File > Export > Create PDF/XPS.",
          "why": "Setting the print area first is what keeps the PDF to the summary rather than 900 rows of source data. The PDF then contains only what was visible — nothing hidden travels with it."},
         {"move": "If you must send the workbook, save a copy and delete what should not travel.",
          "why": "Delete the hidden sheets in the copy rather than re-hiding them. Hiding is reversible by the recipient; deletion is not. Never edit the original for this — work on the copy so your own source data stays intact."},
       ],
       "result": "The manager receives exactly the summary, with no hidden sheets, no vendor pricing, and no formulas exposing the method.",
       "takeaway": "Inspect first, then match the format to the actual need. Hidden is not the same as removed."},
    ],
  },
  "checks": [{"explanation": "PDF captures only what is visible and cannot be casually edited, which makes it right for distributing figures. It also leaves behind hidden sheets, filtered rows, and formulas that an .xlsx would carry along.",
    "rationales": [
      "CSV is plain text and fully editable. It also discards formatting, formulas, and every sheet but the active one.",
      "A macro-enabled workbook is more editable, not less, and macro files raise security concerns for recipients.",
      "Correct. A PDF preserves the visible layout, is not casually editable, and does not carry hidden sheets or formulas.",
      "The legacy .xls format is fully editable and imposes old row limits. It addresses compatibility, not editing control.",
    ]}],
},
}

M2 = {
"cell-basics": {
  "objectives": [
    "Enter, edit, and clear cell content, and distinguish clearing from deleting",
    "Use the fill handle to copy values and extend patterns",
    "Use Paste Special to paste values, formats, or formulas selectively",
    "Explain why Excel treats some entries as text and others as numbers",
  ],
  "opening": {
    "heading": "Excel is always deciding what you typed",
    "blocks": [
      {"type": "scenario",
       "role": "You are entering supply orders at Lakeside Medical Associates.",
       "text": "You type a catalog number as 03-4521 and Excel displays a date. You type another as 1/2 and get January 2nd. Your totals column will not sum, because half its values are text that merely looks numeric.",
       "task": "Understand how Excel interprets what you type, so your data behaves as data."},
      {"type": "paragraph",
       "text": "Every entry is classified the moment you press Enter: number, date, or text. That classification governs everything afterwards — whether it sums, how it sorts, whether a formula can use it. Numbers align right by default and text aligns left, which gives you a free visual check: a column of right-aligned figures with one left-aligned entry has one text value hiding in it."},
      {"type": "paragraph",
       "text": "To force text, format the cells as Text before typing, or begin the entry with an apostrophe: '03-4521. The apostrophe is not stored — it tells Excel to keep what follows verbatim. This is the standard fix for catalog numbers, account codes, and any identifier with leading zeros."},
      {"type": "table",
       "caption": "The fill handle's behaviors",
       "columns": ["You enter and drag", "Excel produces", "Why"],
       "rows": [
         ["One cell containing 5", "5, 5, 5, 5", "A single value is copied"],
         ["Two cells containing 5 and 10", "15, 20, 25", "Two cells establish a pattern — a step of 5"],
         ["A cell containing Monday", "Tuesday, Wednesday…", "Excel knows built-in lists for days and months"],
         ["A cell containing =A1+B1", "=A2+B2, =A3+B3", "Relative references shift as the formula moves down"],
         ["Ctrl held while dragging", "Copies instead of extending", "Overrides Excel's pattern detection"],
       ]},
      {"type": "callout", "variant": "warning",
       "text": "Delete clears a cell's contents but leaves the cell in place. Right-click > Delete removes the cell itself and shifts its neighbours, which will break formulas that referred to the shifted cells. When you mean to empty cells, press Delete; when you mean to remove rows, select the whole row."},
    ],
  },
  "checks": [{"explanation": "The fill handle — the small square at the bottom-right of a selection — copies content into adjacent cells or continues a pattern. Select two cells that establish a step and it extends the series rather than repeating the value.",
    "rationales": [
      "Clearing contents is done with the Delete key or Home > Clear. The fill handle adds content rather than removing it.",
      "Fill color is applied from the Home tab's paint bucket. The fill handle fills cells with content, not with color — an easy confusion given the name.",
      "Correct. It copies a value or continues a detected pattern into the cells you drag across.",
      "Inserting rows is done by right-clicking a row header and choosing Insert. The fill handle does not change the structure of the sheet.",
    ]}],
},
"modifying-columns-rows-and-cells": {
  "objectives": [
    "Adjust column width and row height, including AutoFit",
    "Insert, delete, hide, and unhide rows and columns",
    "Explain why merged cells cause problems in data ranges",
    "Wrap text so long entries stay readable",
  ],
  "opening": {
    "heading": "Merged cells break more than they fix",
    "blocks": [
      {"type": "scenario",
       "role": "You inherit the supply tracker at Lakeside Medical Associates.",
       "text": "Your predecessor merged cells across the top of each section to make headings look centered. Now sorting throws an error, filtering behaves unpredictably, and selecting a column selects far more than you asked for.",
       "task": "Learn the layout tools that make a sheet readable without damaging its structure."},
      {"type": "paragraph",
       "text": "Merging combines cells into one, which destroys the grid the merged region covered. Sorting, filtering, and many formulas depend on every row having the same shape, so a merged range breaks them. In a data table, merged cells are close to always the wrong tool."},
      {"type": "paragraph",
       "text": "'Center Across Selection' gives the same visual result without the damage. Select the cells, open Format Cells > Alignment, and set Horizontal to Center Across Selection. The text appears centered across the range while every cell remains individually addressable — so sorting and filtering keep working."},
      {"type": "callout", "variant": "warning",
       "text": "Hiding a column does not remove its data. Hidden columns are fully present in the file and unhide in two clicks, so hiding is never a way to withhold information from someone you send the workbook to. If data should not travel, delete it from a copy."},
      {"type": "tip",
       "text": "Double-clicking the boundary between two column headers AutoFits that column to its widest entry. Select every column first and one double-click sizes them all — the fastest way to make an inherited sheet readable."},
    ],
  },
  "checks": [{"explanation": "AutoFit sizes a column to exactly fit its widest entry, so nothing is cut off and no space is wasted. Double-clicking the boundary in the column header is the fastest way to apply it.",
    "rationales": [
      "AutoFit measures the actual content rather than applying any fixed width. Excel's default width is about 8.43 characters, but AutoFit ignores it.",
      "Hiding is a separate command on the right-click menu. AutoFit changes width, and never to zero.",
      "Correct. The column is sized to fit its widest entry.",
      "Merging is a separate command on the Home tab, and it is best avoided in data ranges. AutoFit only changes width.",
    ]}],
},
"formatting-cells": {
  "objectives": [
    "Apply fonts, borders, and fill colors purposefully",
    "Use cell styles for consistency across a workbook",
    "Explain why formatting should never be the only carrier of meaning",
    "Use Format Painter to copy formatting across ranges",
  ],
  "opening": {
    "heading": "Formatting should help someone read the numbers",
    "blocks": [
      {"type": "scenario",
       "role": "You prepare the monthly budget review at Lakeside Medical Associates.",
       "text": "You shade the over-budget rows red. The report is printed in black and white for the board meeting, where every row is now identical grey. The one thing the report existed to communicate is invisible.",
       "task": "Format so the meaning survives printing, photocopying, and colorblind readers."},
      {"type": "paragraph",
       "text": "The rule is that color may reinforce meaning but must never be the only thing carrying it. Add a status column reading 'Over budget,' or a symbol, or bold. Then the red shading is a helpful accent rather than the sole signal — and the report still works in greyscale."},
      {"type": "paragraph",
       "text": "Cell Styles (Home > Cell Styles) are Excel's equivalent of Word's styles: named formatting you apply by reference. Using the built-in Heading, Total, and Input styles means a workbook stays consistent, and restyling it later is one change rather than a hunt through every sheet."},
      {"type": "tip",
       "text": "A widely used convention marks input cells — the ones a person types into — in one distinct color, and leaves calculated cells unshaded. Anyone opening the workbook then knows immediately which cells are safe to change and which contain formulas they would break."},
    ],
  },
  "checks": [{"explanation": "Fill Color sets the background of the cell. Font Color changes the text itself, and Border Color affects only the cell's outline.",
    "rationales": [
      "Font Color changes the color of the characters, leaving the cell background unchanged.",
      "Cell Styles apply a saved combination of formatting, which may include a fill — but the specific control for the background is Fill Color.",
      "Correct. Fill Color sets the cell's background color.",
      "Border Color affects the lines around the cell, not the area inside it.",
    ]}],
},
"understanding-number-formats": {
  "objectives": [
    "Apply currency, percentage, date, and accounting formats appropriately",
    "Explain the difference between a displayed value and a stored value",
    "Diagnose why a percentage or date displays unexpectedly",
    "Use custom number formats for identifiers with leading zeros",
  ],
  "opening": {
    "heading": "What you see is not always what is stored",
    "blocks": [
      {"type": "scenario",
       "role": "You reconcile invoices at Lakeside Medical Associates.",
       "text": "A column of costs displays as whole dollars and the total is off by four dollars against the vendor statement. Nothing looks wrong. The cells actually contain cents, and the display is rounding each one for you while the total sums the real values.",
       "task": "Separate what a cell displays from what it stores, because formulas always use the stored value."},
      {"type": "paragraph",
       "text": "Number formatting changes appearance only. A cell holding 1240.4567 formatted to no decimals displays 1240, but every formula referring to it uses 1240.4567. This is why a column of rounded-looking numbers produces a total that appears not to add up — the total is correct, and the display is what is lying."},
      {"type": "paragraph",
       "text": "If you need the value itself rounded, use the ROUND function: =ROUND(A1,2). Formatting is for presentation; ROUND is for changing the number. Confusing the two is one of the most common sources of reconciliation discrepancies."},
      {"type": "table",
       "caption": "Formats and their traps",
       "columns": ["Format", "Displays 0.25 as", "Watch out for"],
       "rows": [
         ["General", "0.25", "No formatting applied"],
         ["Percentage", "25%", "Excel multiplies by 100 to display — typing 25 into a percent cell gives 2500%"],
         ["Currency", "$0.25", "Places the symbol next to the number"],
         ["Accounting", "$   0.25", "Aligns symbols and decimals in a column; shows zero as a dash"],
         ["Text", "0.25", "Excel stops treating it as a number — it will not sum"],
       ]},
      {"type": "callout", "variant": "info",
       "text": "Dates are stored as serial numbers counting from 1 January 1900, which is why a date can suddenly display as 45,292 if the format is reset to General. The data is intact — apply a date format and it returns. It is also why dates can be used in arithmetic: subtracting one date from another gives the number of days between them."},
    ],
  },
  "checks": [{"explanation": "Percentage format multiplies the stored value by 100 for display and adds a percent sign, so 0.25 displays as 25%. This is also the trap: typing 25 into a cell already formatted as percentage gives 2500%.",
    "rationales": [
      "That would be the result of formatting 0.0025. Percentage format multiplies the stored value by 100 for display.",
      "That would be the result of formatting 0.025.",
      "Correct. 0.25 multiplied by 100 displays as 25%.",
      "That would be the result of formatting 2.5. It is what you get by typing 25 into a cell already formatted as percentage.",
    ]}],
},
"intro-to-formulas": {
  "objectives": [
    "Write formulas using cell references rather than typed values",
    "Explain why references make a spreadsheet maintainable",
    "Use the fill handle to copy a formula down a column",
    "Recognize and interpret Excel's common error values",
  ],
  "opening": {
    "heading": "Never type a number a formula could calculate",
    "blocks": [
      {"type": "scenario",
       "role": "You maintain the supply budget at Lakeside Medical Associates.",
       "text": "The totals row contains typed numbers your predecessor calculated by hand. A price correction arrives for one item. The item's cost updates, the totals do not, and the workbook now quietly disagrees with itself — with nothing on screen indicating a problem.",
       "task": "Build formulas that recalculate, so the workbook can never fall out of step with its own data."},
      {"type": "paragraph",
       "text": "Every formula begins with an equals sign, which is how Excel knows to calculate rather than store what you typed. =C2*D2 multiplies whatever is currently in those two cells and updates the instant either changes."},
      {"type": "paragraph",
       "text": "The discipline is to reference rather than embed. =C2*0.08 for tax works until the rate changes, and then it is wrong in every cell that used it, invisibly. Put the rate in its own labeled cell and write =C2*$F$1. When the rate changes you edit one cell, and the entire workbook is correct again."},
      {"type": "table",
       "caption": "Error values and what they actually mean",
       "columns": ["Error", "Means", "Usual cause"],
       "rows": [
         ["#####", "The column is too narrow to display the value", "Widen the column — the value is fine"],
         ["#DIV/0!", "Division by zero or by an empty cell", "A divisor cell is empty or zero"],
         ["#VALUE!", "The formula received the wrong type of data", "Text where a number was expected"],
         ["#REF!", "A reference points at a cell that no longer exists", "A row or column the formula used was deleted"],
         ["#NAME?", "Excel does not recognize a name in the formula", "A misspelled function name, or text without quotation marks"],
         ["#N/A", "A lookup found no match", "The value being looked up is not present in the lookup range"],
       ]},
      {"type": "worked-example",
       "title": "Building a supply cost sheet that maintains itself",
       "task": "Calculate line totals, a subtotal, and tax so that any price change updates everything automatically.",
       "steps": [
         {"move": "Put the tax rate in its own labeled cell, say F1, rather than inside formulas.",
          "why": "A rate typed into thirty formulas has to be found and changed thirty times, and any one you miss stays wrong silently. A rate in a labeled cell is changed once, and it is visible to anyone opening the workbook."},
         {"move": "In E2 enter =C2*D2 for quantity times unit price.",
          "why": "References rather than numbers. If the quantity in C2 changes, the line total follows immediately — the sheet can never disagree with its own inputs."},
         {"move": "Select E2 and double-click the fill handle to copy down the column.",
          "why": "Double-clicking fills down to the extent of the adjacent data, which is far more reliable than dragging on a 900-row sheet. The relative references shift as the formula moves, so row 3 gets =C3*D3."},
         {"move": "Subtotal with =SUM(E2:E30), then tax with =E31*$F$1.",
          "why": "The dollar signs make F1 absolute, so copying the formula never shifts it off the rate cell. SUM over a range also keeps working when rows are inserted inside it, which typed addition does not."},
       ],
       "result": "A sheet where changing any quantity, price, or the tax rate updates every dependent figure instantly.",
       "takeaway": "Put every input in its own labeled cell and reference it. Numbers buried inside formulas are the single most common cause of spreadsheets that are quietly wrong."},
    ],
  },
  "checks": [{"explanation": "Every formula begins with an equals sign. Without it Excel stores what you typed as text, which is why a 'formula' sometimes just sits in the cell displaying itself.",
    "rationales": [
      "Excel accepts a leading + for compatibility with old Lotus habits and converts it to =, but the equals sign is the actual rule.",
      "Starting with a cell reference produces text. A1+B1 typed without an equals sign is stored as the literal characters.",
      "Correct. The equals sign tells Excel to calculate rather than store the text.",
      "Even a function needs the equals sign. SUM(A1:A10) without it is text; =SUM(A1:A10) calculates.",
    ]}],
},
}

apply("lib/content/ms-office/excel/module1Lessons.ts", M1)
apply("lib/content/ms-office/excel/module2Lessons.ts", M2)
