import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from enrich import apply

M1 = {
"getting-started-with-powerpoint": {
  "objectives": [
    "Identify the Ribbon, slide pane, thumbnail pane, and notes pane",
    "Switch between Normal, Slide Sorter, Reading, and Presenter views",
    "Explain what a placeholder is and why it matters",
    "Navigate a deck efficiently while building it",
  ],
  "opening": {
    "heading": "PowerPoint is a visual aid, not the presentation",
    "blocks": [
      {"type": "scenario",
       "role": "You prepare the monthly all-staff briefing at Lakeside Medical Associates.",
       "text": "Your first deck has fourteen slides carrying every word you plan to say. During the meeting the room reads ahead, stops listening, and you end up reading your own slides aloud to people who finished them a minute ago.",
       "task": "Learn the tool, and learn what belongs on a slide versus what belongs in your mouth."},
      {"type": "paragraph",
       "text": "The most useful principle in this entire course is that the audience cannot read and listen at the same time. Text-heavy slides force a choice, and the audience reliably chooses reading — which makes the presenter redundant. Slides should carry the few things that genuinely benefit from being seen: an image, a number, a chart, a short phrase that anchors what you are saying."},
      {"type": "paragraph",
       "text": "Everything else goes in the notes pane, which only you see in Presenter View. This is what the notes pane is actually for, and using it properly is the difference between a deck that supports you and a deck that replaces you."},
      {"type": "key-terms",
       "terms": [
         {"term": "Placeholder", "definition": "A pre-positioned content box defined by the slide layout. Typing into placeholders rather than free text boxes is what keeps a deck consistent."},
         {"term": "Layout", "definition": "A named arrangement of placeholders — Title Slide, Title and Content, Two Content. Chosen per slide."},
         {"term": "Slide Master", "definition": "The design definition behind every layout. Change it once and the whole deck follows."},
         {"term": "Theme", "definition": "The coordinated colors, fonts, and effects applied across the presentation."},
         {"term": "Notes pane", "definition": "Text attached to a slide that the audience never sees. Visible to you in Presenter View."},
       ]},
      {"type": "table",
       "caption": "The views and when to use each",
       "columns": ["View", "Shows", "Use it to"],
       "rows": [
         ["Normal", "One slide plus thumbnails and notes", "Build and edit slides"],
         ["Outline", "Text only, as a hierarchy", "Draft and reorder the argument before designing anything"],
         ["Slide Sorter", "All slides as thumbnails", "Reorder, delete, and check visual consistency"],
         ["Reading", "Full screen in a window", "Review the flow without leaving your desktop"],
         ["Presenter", "Notes, timer, and next slide", "Actually present"],
       ]},
      {"type": "tip",
       "text": "Build the deck in Outline View first. It shows only the text hierarchy, so you are forced to work on the argument before you can be distracted by design. A deck whose outline does not make sense will not be rescued by a theme."},
    ],
  },
  "checks": [{"explanation": "The Ribbon organizes PowerPoint's commands into task-based tabs — Home for text and slides, Insert for objects, Design for themes, Transitions and Animations for motion.",
    "rationales": [
      "The status bar reports the slide number, view controls, and zoom. It displays information rather than housing commands.",
      "The Quick Access Toolbar holds a few shortcuts you choose yourself. It is a convenience layer over the Ribbon.",
      "Correct. The Ribbon organizes commands into task-based tabs.",
      "The navigation pane shows slide thumbnails for reordering and selecting. It manages slides rather than holding commands.",
    ]}],
},
"understanding-onedrive-for-powerpoint": {
  "objectives": [
    "Save a presentation to OneDrive and open it elsewhere",
    "Explain why cloud storage matters for a deck you will present",
    "Share a presentation with appropriate permissions",
    "Plan for presenting when the network is unavailable",
  ],
  "opening": {
    "heading": "The file has to be there when you stand up to present",
    "blocks": [
      {"type": "scenario",
       "role": "You present at the quarterly staff meeting at Lakeside Medical Associates.",
       "text": "Your deck is on your desk computer. The meeting is in the conference room, on a different machine, and the guest network is refusing connections. You have four minutes and thirty people waiting.",
       "task": "Store the deck so it is reachable from anywhere, and carry a fallback for when the network is not."},
      {"type": "paragraph",
       "text": "OneDrive makes the presentation reachable from any machine you can sign in on, which solves the ordinary case well. It also gives you version history, so an accidental deletion of six slides is recoverable rather than final."},
      {"type": "callout", "variant": "warning",
       "text": "Never let the cloud be your only copy of something you must present. Networks fail in conference rooms specifically. Before any presentation that matters, put a copy on a USB drive or the local desktop, and export a PDF as a last-resort fallback — a PDF will open on literally any machine, and a static deck is far better than no deck."},
      {"type": "tip",
       "text": "Embedded video and audio are the usual cause of a deck that works on your machine and fails on the presentation machine. File > Info > Optimize Media Compatibility embeds and converts media so it travels with the file. Always run it before presenting from a different computer."},
    ],
  },
  "checks": [{"explanation": "OneDrive stores the presentation on Microsoft's servers so you can open it from any device you sign in on, and share it by link. It also provides version history and co-authoring.",
    "rationales": [
      "Storage location has no effect on transitions, which are applied from the Transitions tab.",
      "OneDrive does not compress files. Reducing file size is done with Compress Pictures and media optimization.",
      "Correct. The presentation is reachable from any device you sign in on, and can be shared by link.",
      "Sharing permissions are something you set deliberately. Saving to OneDrive does not lock a file against editing.",
    ]}],
},
"creating-and-opening-presentations": {
  "objectives": [
    "Create presentations from blank files and from templates",
    "Open and pin recent presentations",
    "Evaluate whether a template suits your content",
    "Explain what a template supplies beyond appearance",
  ],
  "opening": {
    "heading": "A template is a set of decisions already made",
    "blocks": [
      {"type": "scenario",
       "role": "You produce recurring briefings at Lakeside Medical Associates.",
       "text": "Every month you rebuild the same deck: the same title arrangement, the same colors, the same closing slide. Twenty minutes each time, spent re-making decisions you already made in January — and the decks still do not quite match each other.",
       "task": "Build the practice's design once as a template, then start every deck from it."},
      {"type": "paragraph",
       "text": "A template supplies the theme, the slide layouts, and often placeholder content — all the structural decisions. Starting from one means starting with the design settled, so your attention goes to the argument rather than to fonts."},
      {"type": "callout", "variant": "info",
       "text": "Judge a template by its layouts, not its title slide. Many attractive templates supply three usable layouts and nothing else, so the moment you need a comparison slide or a full-width chart you are improvising with text boxes — and the consistency you chose the template for is gone. Open the Slide Master and look at what layouts exist before committing to a template."},
    ],
  },
  "checks": [{"explanation": "A template is a pre-designed presentation supplying the theme, slide layouts, and often sample content, used as a starting point. Opening one creates a new presentation and leaves the template intact.",
    "rationales": [
      "A blank slide with no formatting is what you get from a blank presentation, which is the opposite of a template.",
      "That describes a self-running or kiosk presentation, configured under Set Up Slide Show.",
      "Correct. A template is a pre-designed presentation you customize as a starting point.",
      "Read-only status is a file property, unrelated to what a template is.",
    ]}],
},
"saving-presentations": {
  "objectives": [
    "Save in the format that matches how the deck will be used",
    "Export to PDF and to video",
    "Explain what each export format preserves and loses",
    "Prepare a deck for a machine that may not have PowerPoint",
  ],
  "opening": {
    "heading": "Choose the format for how it will be opened",
    "blocks": [
      {"type": "scenario",
       "role": "You distribute the orientation deck at Lakeside Medical Associates.",
       "text": "You email the .pptx to twelve new hires. Three cannot open it, two see substituted fonts that break every slide layout, and one edits it and forwards their version to the rest.",
       "task": "Match the distribution format to what recipients actually need to do with it."},
      {"type": "table",
       "caption": "Export formats",
       "columns": ["Format", "Preserves", "Use for"],
       "rows": [
         [".pptx", "Everything, fully editable", "Colleagues who must edit it"],
         ["PDF", "Layout and fonts; loses animation and video", "Distributing to read — opens anywhere"],
         ["MP4 video", "Animation, timing, and narration", "Self-paced training people watch without you"],
         ["PowerPoint Show (.ppsx)", "Everything; opens straight into the slide show", "Handing to someone who should present, not edit"],
         ["Images (PNG/JPG)", "One picture per slide", "Dropping a slide into another document"],
       ]},
      {"type": "callout", "variant": "warning",
       "text": "Fonts are the most common cause of a deck that looks wrong on someone else's machine. If a font is not installed there, PowerPoint substitutes another and your layout reflows — text overflows placeholders and line breaks land in the wrong places. File > Options > Save > Embed fonts in the file prevents it, and PDF sidesteps the problem entirely."},
    ],
  },
  "checks": [{"explanation": "PDF preserves layout and fonts exactly and is not casually editable, so it is right for distributing a deck people should read rather than change. It does lose animation, transitions, and embedded video.",
    "rationales": [
      "A .pptx is fully editable, which is precisely what you are trying to avoid — and it also risks font substitution on the recipient's machine.",
      "Sharing with collaborators grants editing access, which is the opposite of the goal.",
      "Correct. PDF locks the layout and fonts and is not casually editable.",
      "Mark as Final is only an advisory flag. It shows a notice and is dismissed with one click, so it prevents nothing.",
    ]}],
},
"slide-basics": {
  "objectives": [
    "Add, duplicate, delete, and reorder slides",
    "Choose a layout that matches the slide's content",
    "Explain why placeholders beat free-floating text boxes",
    "Use the outline to structure a deck before designing it",
  ],
  "opening": {
    "heading": "Layouts are what keep a deck from drifting",
    "blocks": [
      {"type": "scenario",
       "role": "You build a twenty-slide orientation deck at Lakeside Medical Associates.",
       "text": "You add text boxes wherever you need them rather than using layouts. Your titles land at slightly different heights on almost every slide. Watching the deck, the title jitters up and down from slide to slide, and the whole thing feels amateurish for reasons nobody can name.",
       "task": "Use layouts and placeholders so alignment is structural rather than something you re-achieve each time."},
      {"type": "paragraph",
       "text": "A layout is a set of placeholders positioned by the Slide Master. Type into placeholders and every title lands in exactly the same place on every slide, with the same font and size. That invisible consistency is most of what separates a professional deck from a homemade one."},
      {"type": "paragraph",
       "text": "Free text boxes place themselves wherever you drop them, which is why title jitter happens. They have a legitimate role — a caption over an image, an annotation on a diagram — but they should never be doing a placeholder's job."},
      {"type": "worked-example",
       "title": "Building a slide that stays consistent with the rest of the deck",
       "task": "Add a slide comparing two intake processes, without breaking the deck's alignment.",
       "steps": [
         {"move": "Home > New Slide, and pick the Two Content layout rather than accepting the default.",
          "why": "The layout is chosen for the content, not the other way round. Two Content gives two side-by-side placeholders already aligned to the master, so the comparison structure is built in before you type anything."},
         {"move": "Click into each placeholder and type.",
          "why": "Placeholder text inherits the master's font, size, and position automatically, and it appears in the outline. Text in a free box does neither, which is also why it will not appear if anyone builds a summary from the outline."},
         {"move": "If the text does not fit, cut the text rather than shrinking the font.",
          "why": "PowerPoint offers to autofit by reducing the size, which is how a deck ends up with eight different body sizes. Overflow is a signal that the slide is carrying too much — move the detail to the notes, which is where it belonged."},
         {"move": "Use Outline View to check the slide's place in the argument.",
          "why": "The outline shows the deck as structure, stripped of design. If a slide's title does not make sense in that list, the problem is with the content rather than the layout."},
       ],
       "result": "A comparison slide that matches every other slide's alignment and typography exactly.",
       "takeaway": "Pick the layout that fits the content, type into placeholders, and treat overflow as a content problem rather than a font-size problem."},
    ],
  },
  "checks": [{"explanation": "A layout is a pre-arranged set of placeholders defining where content sits on a slide. Because placeholder positions come from the Slide Master, using layouts keeps every slide aligned consistently.",
    "rationales": [
      "That describes a theme, which sets colors and fonts across the whole presentation. A layout arranges content areas.",
      "A color palette is part of the theme. Layouts govern arrangement, not color.",
      "Correct. A layout is a pre-arranged set of placeholders for a slide's content.",
      "That describes Slide Sorter view. A layout is a property of a slide rather than a way of viewing the deck.",
    ]}],
},
}

M2 = {
"powerpoint-text-basics": {
  "objectives": [
    "Add and edit text in placeholders and text boxes",
    "Select text efficiently with keyboard shortcuts",
    "Apply formatting that stays consistent with the deck's theme",
    "Recognize when a slide is carrying too much text",
  ],
  "opening": {
    "heading": "The word limit is the design",
    "blocks": [
      {"type": "scenario",
       "role": "You present quarterly results at Lakeside Medical Associates.",
       "text": "Your key slide holds ninety words in five bullets. You watch the room read it, and by the time you reach your second sentence they have finished and are checking their phones. The information was delivered. The point was not.",
       "task": "Reduce each slide to what genuinely benefits from being seen, and move the rest to the notes."},
      {"type": "paragraph",
       "text": "A commonly cited guide is roughly six words per line and six lines per slide. The number matters less than the principle behind it: a slide is glanced at, not read. Anything requiring sustained reading belongs in a handout or in the notes pane."},
      {"type": "paragraph",
       "text": "Font size is the other half. Twenty-four point is a sensible floor for body text — not for aesthetics, but because it is what remains legible from the back of a room. If your content only fits at eighteen point, the slide has too much on it, and shrinking the type just makes it unreadable as well as crowded."},
      {"type": "table",
       "caption": "Where content belongs",
       "columns": ["Content", "Put it", "Because"],
       "rows": [
         ["The single point of the slide", "The slide, as a short phrase", "It anchors what you are saying"],
         ["Your supporting explanation", "The notes pane", "You say it; the audience listens rather than reads"],
         ["Detailed figures and tables", "A handout", "Detail needs reading time a live audience does not have"],
         ["The source of a statistic", "A small line on the slide", "It establishes credibility without being read aloud"],
       ]},
    ],
  },
  "checks": [{"explanation": "Clicking the text box places your cursor inside it, and Ctrl+A then selects all the text within that box rather than every object on the slide.",
    "rationales": [
      "PowerPoint's right-click menu for a text box has no Select All command.",
      "Correct. Click into the box to place the cursor, then Ctrl+A selects all the text inside it.",
      "Double-clicking the border selects the text box as an object, which lets you format the box rather than edit its text. Useful, but not the same thing.",
      "Home > Select offers Select All for objects on the slide, not for text inside one box.",
    ]}],
},
"powerpoint-lists": {
  "objectives": [
    "Create bulleted and numbered lists and change their levels",
    "Choose between bullets and numbers based on whether order matters",
    "Explain why long bulleted lists undermine a presentation",
    "Convert a list into a stronger visual when appropriate",
  ],
  "opening": {
    "heading": "The bullet list is the default, and rarely the best choice",
    "blocks": [
      {"type": "scenario",
       "role": "You explain the referral workflow at Lakeside Medical Associates.",
       "text": "Six bullets describing six sequential steps. The audience sees six equal-looking items and cannot tell that order matters, that step three depends on step two, or where the decision point is. A simple diagram would have shown all three instantly.",
       "task": "Use numbers when sequence matters, and consider whether a list is the right form at all."},
      {"type": "paragraph",
       "text": "Bullets signal a set with no order. Numbers signal sequence. Using bullets for a procedure actively misinforms, because readers take the formatting as meaning — the same rule that applies in Word applies here, and matters more, because a slide gets a glance rather than a careful read."},
      {"type": "paragraph",
       "text": "It is also worth asking whether a list is the right form at all. A sequence is usually clearer as a process diagram, a comparison as a two-column table, and a proportion as a chart. Bullets are the default because they are easy to type, not because they communicate well."},
      {"type": "tip",
       "text": "Tab demotes a bullet to the next level and Shift+Tab promotes it, which works as you type. If you find yourself needing a third or fourth level on a slide, the content has outgrown the format — split it into several slides or move it to a handout."},
    ],
  },
  "checks": [{"explanation": "Numbers communicate sequence. Use them whenever steps must happen in a particular order; bullets tell the audience the order does not matter, which misleads them on a procedure.",
    "rationales": [
      "Visual variety is not a reason to change list type. The list type carries meaning, and choosing it for looks misinforms.",
      "That is exactly when bullets are appropriate — numbers would imply an order that does not exist.",
      "Correct. Numbers signal sequence, so use them whenever order matters.",
      "Item count has no bearing on the choice. If anything, more than five or six items suggests the slide should be split.",
    ]}],
},
"indents-and-line-spacing": {
  "objectives": [
    "Adjust line spacing and paragraph spacing in a placeholder",
    "Use indent levels to show hierarchy",
    "Explain how whitespace affects legibility from a distance",
    "Recognize when spacing changes are hiding a content problem",
  ],
  "opening": {
    "heading": "Whitespace is what makes a slide readable from the back",
    "blocks": [
      {"type": "scenario",
       "role": "You prepare a training slide at Lakeside Medical Associates.",
       "text": "You cram five bullets in by cutting line spacing to 0.8. On your monitor it is fine. Projected in a room with the lights on, the lines run together into a grey block and the people at the back read none of it.",
       "task": "Use spacing to aid legibility, and treat crowding as a signal to cut content."},
      {"type": "paragraph",
       "text": "Line spacing between about 1.0 and 1.2 suits most slide text. Tighter than that and lines start to merge visually at a distance, particularly with a projector's reduced contrast. Space between paragraphs matters more on a slide than in a document, because it is what separates one idea from the next at a glance."},
      {"type": "callout", "variant": "warning",
       "text": "Reducing line spacing to fit more content is treating the symptom. Crowding means the slide is carrying more than a slide can carry — the fix is to split it or move detail to the notes. A slide that only fits at 0.8 spacing and 16 point will not be read by anyone beyond the second row."},
    ],
  },
  "checks": [{"explanation": "Line spacing controls the vertical gap between lines within a paragraph. On a slide, adequate spacing is what keeps lines from merging visually when projected at a distance.",
    "rationales": [
      "Font size is a separate setting. Line spacing changes the gaps between lines, not the size of the characters.",
      "Correct. It adds space between lines, which improves legibility — especially when projected.",
      "Position on the slide is controlled by moving the placeholder. Line spacing works inside it.",
      "Indent level is changed with Tab and Shift+Tab or the indent buttons. Spacing and indentation are independent.",
    ]}],
},
"using-find-and-replace": {
  "objectives": [
    "Find text across all slides in a presentation",
    "Replace text throughout a deck",
    "Use Replace Fonts to swap a typeface everywhere",
    "Check that a replacement has not broken anything",
  ],
  "opening": {
    "heading": "One command for a change that touches every slide",
    "blocks": [
      {"type": "scenario",
       "role": "You update the orientation deck at Lakeside Medical Associates.",
       "text": "The practice changes its name. The old name appears on thirty-one of forty slides, including several inside diagrams. Slide by slide, this is half an hour and a guarantee of missing two.",
       "task": "Replace throughout the deck in one action, then verify the result."},
      {"type": "paragraph",
       "text": "Replace (Ctrl+H) works across every slide at once. Match case is available and worth using for a proper noun, so you change the practice name without touching an ordinary word that happens to contain the same letters."},
      {"type": "callout", "variant": "info",
       "text": "Replace Fonts, on the Replace dropdown, swaps one typeface for another everywhere in the deck. It is the correct fix when you inherit a presentation using a font your machine does not have, and far faster than selecting text on every slide. Check the deck afterwards — different fonts have different widths, so text that fitted before may now overflow its placeholder."},
      {"type": "tip",
       "text": "Find and Replace does not reach text inside images or embedded objects. After a replacement, use Outline View to confirm the old text is gone from all the real text, and then look through the slides for any that appears in a picture or a screenshot."},
    ],
  },
  "checks": [{"explanation": "Replace swaps one word or phrase for another throughout the entire presentation in a single action, rather than requiring you to edit each slide.",
    "rationales": [
      "Replace changes the text itself, not its formatting. Formatting every instance is a separate task.",
      "Deleting is possible by replacing with nothing, but that is a special case rather than what Replace is for.",
      "Correct. It swaps one word or phrase for another across every slide at once.",
      "Moving text between slides is done by cutting and pasting. Replace changes text in place.",
    ]}],
},
}

apply("lib/content/ms-office/powerpoint/module1Lessons.ts", M1)
apply("lib/content/ms-office/powerpoint/module2Lessons.ts", M2)
