import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from enrich import apply

M5 = {
"inserting-tables": {
  "objectives": [
    "Insert a table using the grid, the dialog box, or by converting existing text",
    "Navigate a table with Tab and Shift+Tab without reaching for the mouse",
    "Choose a table over tabs when data has real rows and columns",
    "Mark a header row so the table stays readable across pages and for screen readers",
  ],
  "opening": {
    "heading": "Tables are for data, not for layout",
    "blocks": [
      {"type": "scenario",
       "role": "You maintain the provider schedule at Lakeside Medical Associates.",
       "text": "You build the weekly schedule using tabs and spaces to line up the columns. It looks correct. Then a provider's name gets one character longer, and every row below shifts out of alignment. You spend twenty minutes nudging tab stops that will break again next week.",
       "task": "Use a real table so alignment is structural and survives editing."},
      {"type": "paragraph",
       "text": "Anything with genuine rows and columns belongs in a table. Cells hold their alignment no matter what you type into them, columns resize as a unit, and the structure carries meaning that spaces and tabs cannot. Spaces produce alignment that is accidental — it holds only until the content changes."},
      {"type": "paragraph",
       "text": "There is an accessibility dimension too. A screen reader announces a real table's structure — 'row 3, column 2, Dr. Okafor' — so a blind user can navigate it. Columns faked with tabs are read as one long run of words with no relationships at all."},
      {"type": "callout", "variant": "warning",
       "text": "On any table that might run past one page, select the first row and turn on Table Layout > Repeat Header Rows. The headings then reprint at the top of every page, so page two is not an unlabeled grid of numbers. In Table Properties > Row, also uncheck 'Allow row to break across pages' to stop a single row splitting across a page boundary."},
      {"type": "tip",
       "text": "Tab moves to the next cell and Shift+Tab moves back. Pressing Tab in the last cell adds a new row — which is the fastest way to build a table, since you never need to decide the row count in advance. To insert an actual tab character inside a cell, press Ctrl+Tab."},
    ],
  },
  "checks": [{"explanation": "Tab in the final cell adds a new row and puts the cursor in its first cell, so you can keep typing without breaking rhythm. This is why you never need to know the row count when you insert a table.",
    "rationales": [
      "Shift+Tab moves backwards to the previous cell. Tab alone always moves forward.",
      "Correct. Word adds a new row and moves the cursor into it, letting you keep typing continuously.",
      "Converting a table to text is a deliberate command under Table Layout > Convert to Text. Tab never does this.",
      "Tab never adds columns. Columns are added from the Table Layout tab or by right-clicking and choosing Insert.",
    ]}],
},

"modifying-tables": {
  "objectives": [
    "Add and delete rows and columns precisely",
    "Merge and split cells to build headers that span columns",
    "Resize columns to fit content using AutoFit",
    "Apply table styles that aid reading rather than decorate",
  ],
  "opening": {
    "heading": "Table formatting should make data easier to read",
    "blocks": [
      {"type": "scenario",
       "role": "You are formatting the quarterly supply report at Lakeside Medical Associates.",
       "text": "The table is accurate and nobody can read it. Every cell has a heavy border, the header row looks identical to the data, and the columns are all the same width whether they hold a date or a paragraph. The reader has to work to find anything.",
       "task": "Format the table so its structure does the reading work — headers that announce themselves, columns sized to their content."},
      {"type": "paragraph",
       "text": "Merging cells combines adjacent cells into one, which is how you build a header spanning several columns — a single 'Q3 Expenses' cell above three month columns. Splitting does the reverse. Both are on the Table Layout tab, and both operate on whatever you have selected."},
      {"type": "paragraph",
       "text": "For column widths, AutoFit to Contents (Table Layout > AutoFit) sizes each column to what it actually holds, so the date column stops being as wide as the description column. It is one click and it fixes most of what makes a table look amateurish."},
      {"type": "table",
       "caption": "Table formatting that helps, and formatting that hurts",
       "columns": ["Do", "Instead of", "Because"],
       "rows": [
         ["Bold header row with a fill", "Headers styled like data", "The reader needs to see where the labels are"],
         ["Light horizontal rules or banded rows", "A full grid of heavy borders", "Borders on every cell compete with the data for attention"],
         ["Right-align numbers", "Left-align everything", "Aligned decimal points make columns of figures comparable at a glance"],
         ["AutoFit to Contents", "Equal-width columns", "Column width should reflect what the column holds"],
       ]},
      {"type": "callout", "variant": "warning",
       "text": "Merged cells complicate screen reader navigation and can break sorting. Use them for genuine spanning headers, and avoid them inside the data area of a table someone may need to sort or read with assistive technology."},
    ],
  },
  "checks": [{"explanation": "Merge Cells combines the selected adjacent cells into one larger cell, keeping the contents of each. Its main use is a header that spans several columns.",
    "rationales": [
      "Correct. Selected adjacent cells become a single cell, which is how you build a spanning header.",
      "That describes copying and pasting. Merging changes the structure of the table, not the contents of cells.",
      "Sequential numbering is not a Word table feature at all — that is Excel's fill handle. Merging alters structure only.",
      "Removing borders is a formatting change under Table Design > Borders. The cells remain separate; merging genuinely combines them.",
    ]}],
},

"inserting-charts": {
  "objectives": [
    "Insert a chart in Word and edit its underlying data",
    "Choose a chart type that matches the question the data answers",
    "Add titles and labels so the chart is readable without explanation",
    "Decide when to build the chart in Excel and link it instead",
  ],
  "opening": {
    "heading": "The chart type is an argument about the data",
    "blocks": [
      {"type": "scenario",
       "role": "You are preparing the quarterly report at Lakeside Medical Associates.",
       "text": "You need to show how supply spending changed across six months. You choose a pie chart because it looks good. A pie chart cannot show change over time — it shows composition at one moment. The reader sees six slices and no trend, and asks you to redo it.",
       "task": "Match the chart type to the question, so the picture answers what the reader is actually asking."},
      {"type": "paragraph",
       "text": "Inserting a chart in Word opens a small spreadsheet window holding the chart's data. Replace the sample values with yours and the chart redraws. That data lives inside the Word file, which is convenient for a small static chart and a poor choice for figures that update — for those, build the chart in Excel and paste it as a link, so refreshing the workbook updates the document."},
      {"type": "table",
       "caption": "Choosing a chart type",
       "columns": ["The question", "Chart", "Why"],
       "rows": [
         ["How did this change over time?", "Line", "A continuous line is read as continuity — the shape is the trend"],
         ["How do these categories compare?", "Column or bar", "Length is the easiest visual quantity to compare accurately"],
         ["What share of the total is each part?", "Pie", "Only for parts of one whole, and only with five or fewer slices"],
         ["Are these two things related?", "Scatter", "Shows the relationship between two measures directly"],
       ]},
      {"type": "callout", "variant": "warning",
       "text": "A column chart whose value axis does not start at zero exaggerates differences, because the reader compares bar lengths and those lengths no longer represent the values. Truncating the axis on a column chart is a well-known way to mislead, including by accident. Line charts may start elsewhere when the variation matters more than the absolute level, but say so in the axis label."},
      {"type": "tip",
       "text": "Give every chart a title that states the finding, not the subject. 'Supply spending rose 18% in Q3' tells the reader what to see. 'Supply Spending' makes them work it out for themselves, and some will not bother."},
    ],
  },
  "checks": [{"explanation": "Word opens a small embedded spreadsheet holding the chart's data, prefilled with sample values. Replace them with your own and the chart redraws immediately. That data is stored inside the Word file.",
    "rationales": [
      "Word does not prompt for a CSV. You can paste data into the embedded sheet, but no file browser opens.",
      "Correct. A small spreadsheet window opens with sample data for you to replace.",
      "There is no color-and-font wizard. You pick the chart type first, then style it afterwards from the Chart Design tab.",
      "Format Cells is an Excel dialog for number formatting. Inserting a chart in Word does not open it.",
    ]}],
},

"mail-merge-basics": {
  "objectives": [
    "Explain the roles of the main document and the data source",
    "Run a mail merge from start to finish using the Mailings tab",
    "Preview merged results and catch data problems before printing",
    "Judge when mail merge saves time and when it is overkill",
  ],
  "opening": {
    "heading": "One letter, many recipients, no retyping",
    "blocks": [
      {"type": "scenario",
       "role": "You handle recall notices at Lakeside Medical Associates.",
       "text": "Two hundred and forty patients are due for an annual visit. Each needs a letter with their name, address, and appointment date. Typed individually, that is two full days of work and a guarantee that at least one letter carries the wrong name.",
       "task": "Produce all 240 personalized letters from one template and one list, in about fifteen minutes."},
      {"type": "paragraph",
       "text": "Mail merge combines two things. The main document is the letter — everything that stays the same, plus merge fields marking where personal data belongs. The data source is the list — a Word table, an Excel sheet, or Outlook contacts — with one row per recipient and one column per field. Merging produces one output letter per row."},
      {"type": "paragraph",
       "text": "Most merge failures are data problems, not Word problems. Your data source needs a clean header row where every column has a distinct name, no blank rows in the middle, and consistent formatting — because whatever is in the cell is what appears in the letter. A date stored as text as '3/4' will print as '3/4', not as March 4."},
      {"type": "worked-example",
       "title": "Producing 240 recall letters",
       "task": "Merge a recall letter template with a patient list, verifying the output before anything reaches the printer.",
       "steps": [
         {"move": "Prepare the data source first, and open it to check it.",
          "why": "The merge inherits every flaw in the list. Confirm one header row, distinct column names, no blank rows, and dates formatted the way they should appear. Fixing this after generating 240 letters means generating them again."},
         {"move": "Mailings > Start Mail Merge > Letters, then Select Recipients > Use an Existing List.",
          "why": "This binds the letter to the data. Choosing Letters as the type tells Word to produce one page per record, as opposed to labels or envelopes, which lay out several records per sheet."},
         {"move": "Insert merge fields where personal data belongs, including the address block.",
          "why": "Fields appear in chevrons as «FirstName». Use Address Block rather than assembling address lines from individual fields — it handles missing second address lines correctly instead of leaving a blank line in the middle of the address."},
         {"move": "Click Preview Results and step through several records, including the last one.",
          "why": "This is the step that catches everything: a missing surname, a date that came through as a serial number, a patient whose name overflows the line. Check the first, a few in the middle, and the last — the last record is where truncated data sources reveal themselves."},
         {"move": "Finish & Merge > Edit Individual Documents, not straight to print.",
          "why": "This produces a single document containing all 240 letters, which you can scroll and check before committing paper. Printing directly from the merge means the first sign of a problem is a stack of wrong letters."},
       ],
       "result": "240 verified personalized letters produced in one pass, checked before printing.",
       "takeaway": "Clean the data first, preview several records including the last, and merge to a document before merging to the printer."},
      {"type": "callout", "variant": "warning",
       "text": "A merged recall letter contains patient names and appointment details. Merge output is protected information: do not leave the merged document on a shared drive, do not email it as one file to anyone, and shred any misprints rather than binning them. The convenience of generating 240 letters at once is also the risk of exposing 240 patients at once."},
    ],
  },
  "checks": [{"explanation": "The data source is the list — one row per recipient, one column per field. The main document holds the letter and the merge fields. Word combines them to produce one output letter per row of the data source.",
    "rationales": [
      "That describes the main document, which holds the letter text and the field placeholders.",
      "Correct. The data source is the recipient list, with one row per person and one column per piece of information.",
      "Page layout and print settings belong to the main document and the print dialog, not to the data source.",
      "Styles and themes come from the main document. The data source supplies only content.",
    ]}],
},
}

M6 = {
"page-layout": {
  "objectives": [
    "Set margins, orientation, and paper size for a specific purpose",
    "Explain when landscape orientation is genuinely the right choice",
    "Use the Page Setup dialog for settings not on the Ribbon",
    "Account for binding and hole-punching when setting margins",
  ],
  "opening": {
    "heading": "Margins are a reading decision",
    "blocks": [
      {"type": "scenario",
       "role": "You are producing the staff handbook at Lakeside Medical Associates.",
       "text": "To save paper you set every margin to half an inch. The handbook is then three-hole punched for binders, and the punch removes the first character of every line on odd pages. Sixty pages, reprinted.",
       "task": "Set margins for how the document will physically be used, not only for how it looks on screen."},
      {"type": "paragraph",
       "text": "Margins do three jobs: they leave room for hands and binding, they give the eye a rest at the end of each line, and they control line length. Very wide text is genuinely harder to read, because the eye loses its place travelling back to the start of the next line. The one-inch default is a reasonable compromise for most documents, not an arbitrary number."},
      {"type": "paragraph",
       "text": "Orientation should follow the content. Portrait suits text, because it produces comfortable line lengths. Landscape suits wide tables, timelines, and charts that do not fit across a portrait page. A landscape page of body text has lines so long they are tiring to read — if you are reaching for landscape to fit text, the real fix is usually columns."},
      {"type": "table",
       "caption": "Margin settings by purpose",
       "columns": ["Purpose", "Setting", "Note"],
       "rows": [
         ["Standard letter or report", "1 inch all round", "Word's default; safe for any printer"],
         ["Bound or hole-punched", "Gutter margin 0.5 in, left", "Page Setup > Margins > Gutter adds space for binding without shifting the text block"],
         ["Double-sided binding", "Mirror margins", "Inside margins face each other so binding space lands correctly on both sides"],
         ["Maximum content per page", "0.5 in", "Only for documents that stay flat and unbound"],
       ]},
      {"type": "tip",
       "text": "Almost every printer has an unprintable edge, typically a quarter inch. Margins narrower than that will have content clipped, regardless of what the screen shows. If you must go narrow, print one test page before running the job."},
    ],
  },
  "checks": [{"explanation": "Landscape rotates the page so the long edge runs horizontally, making it wider than tall. It suits wide tables and charts; portrait suits body text because it produces more comfortable line lengths.",
    "rationales": [
      "Portrait is the taller-than-wide default, right for most text documents.",
      "Correct. Landscape orients the page so it is wider than it is tall, which suits wide tables and charts.",
      "Custom refers to a user-defined paper size, not an orientation.",
      "Letter is a paper size, 8.5 by 11 inches. Size and orientation are independent settings.",
    ]}],
},

"indents-and-tabs": {
  "objectives": [
    "Set first-line and hanging indents using the ruler and the Paragraph dialog",
    "Explain what a hanging indent is for and where it is required",
    "Set and clear tab stops, including decimal and right-aligned tabs",
    "Recognize why spaces are never a substitute for tabs or indents",
  ],
  "opening": {
    "heading": "Never align with the space bar",
    "blocks": [
      {"type": "scenario",
       "role": "You are compiling a reference list for a staff training packet at Lakeside Medical Associates.",
       "text": "You align the second line of each reference with spaces until it looks right. You then change the font from Calibri to Times New Roman, and every alignment collapses, because the new font's space character is a different width. Forty references, all wrong.",
       "task": "Use indents and tab stops, so alignment is a property of the paragraph and survives every font change."},
      {"type": "paragraph",
       "text": "The distinction is worth stating plainly. A space is a character whose width depends on the font. An indent is a measured property of the paragraph. A tab stop is a defined position on the ruler. Indents and tab stops are exact and stable; spaces are approximate and break the moment anything changes."},
      {"type": "paragraph",
       "text": "A hanging indent puts the first line at the margin and indents every subsequent line. It is what citation styles require for reference lists, because it makes the author surnames line up down the left edge so a reader can scan them. Set it in Paragraph > Indentation > Special > Hanging, or by dragging the lower triangle on the ruler."},
      {"type": "table",
       "caption": "Tab stop types",
       "columns": ["Type", "Aligns text", "Use for"],
       "rows": [
         ["Left", "Left edge at the stop", "Ordinary columns of text"],
         ["Center", "Centered on the stop", "Column headings"],
         ["Right", "Right edge at the stop", "Page numbers in a contents list"],
         ["Decimal", "Decimal points at the stop", "Columns of currency or measurements"],
         ["Bar", "Draws a vertical line", "A visual divider between columns"],
       ]},
      {"type": "tip",
       "text": "Decimal tabs are the reason a column of prices lines up on the decimal point regardless of how many digits each number has. Click the tab selector at the left end of the ruler until it shows the decimal tab, then click on the ruler where the decimal points should sit."},
    ],
  },
  "checks": [{"explanation": "A hanging indent leaves the first line at the margin and indents all following lines. Reference lists use it so the author surnames align down the left edge and can be scanned quickly.",
    "rationales": [
      "Indenting every line equally is a block indent, used for long quotations.",
      "That is a first-line indent, the traditional way to mark the start of a paragraph in continuous prose. A hanging indent is its mirror image.",
      "Correct. The first line sits at the margin and every subsequent line is indented.",
      "Indenting from the right is a right indent, which is usually combined with a left indent for block quotations.",
    ]}],
},

"line-paragraph-spacing": {
  "objectives": [
    "Set line spacing and space before and after paragraphs",
    "Explain why blank paragraphs are a poor way to create vertical space",
    "Choose spacing appropriate to the document's purpose",
    "Use Keep with next to stop headings being stranded at the foot of a page",
  ],
  "opening": {
    "heading": "Press Enter twice and you have made a formatting problem",
    "blocks": [
      {"type": "scenario",
       "role": "You are formatting a twelve-page policy document at Lakeside Medical Associates.",
       "text": "You separate paragraphs by pressing Enter twice throughout. Your supervisor asks for slightly tighter spacing. There is no setting to change — the spacing is made of empty paragraphs, so you must find and delete a hundred and forty of them by hand, and some of them are now stranded at the tops of pages.",
       "task": "Create vertical space with paragraph spacing settings, so it can be adjusted everywhere in one action."},
      {"type": "paragraph",
       "text": "Space Before and Space After are properties of a paragraph, set in the Paragraph dialog or under Layout > Spacing. Because they are properties, they can be changed globally — or built into a style, so every paragraph using that style updates at once. Blank paragraphs are content, and content has to be edited one instance at a time."},
      {"type": "paragraph",
       "text": "Empty paragraphs cause a second problem: they land at page boundaries. A blank paragraph pushed to the top of a page leaves an unexplained gap, and screen readers announce empty paragraphs, so a document padded this way is read aloud with meaningless pauses."},
      {"type": "table",
       "caption": "Spacing conventions",
       "columns": ["Document", "Line spacing", "Paragraph spacing"],
       "rows": [
         ["Business letter", "Single", "6-12 pt after"],
         ["Academic paper", "Double", "0 pt, first-line indent instead"],
         ["Document for review", "1.5 lines", "Extra room for handwritten notes"],
         ["Dense reference table", "Single", "Minimal — the structure does the separating"],
       ]},
      {"type": "tip",
       "text": "Paragraph > Line and Page Breaks > Keep with next binds a paragraph to the one after it, so a heading can never be left alone at the bottom of a page. Setting it on your heading styles fixes the problem permanently across the whole document."},
    ],
  },
  "checks": [{"explanation": "Space Before and Space After are paragraph properties, so they can be adjusted document-wide in one action or built into a style. Blank paragraphs are content, which must be found and deleted individually.",
    "rationales": [
      "Double line spacing increases the gap between every line inside a paragraph, not the gap between paragraphs.",
      "Correct. Space Before and After are paragraph properties, adjustable everywhere at once and safe at page boundaries.",
      "Increase Indent moves the paragraph horizontally. It has no effect on vertical space.",
      "Column spacing controls the gutter between columns in a multi-column layout — horizontal, not vertical.",
    ]}],
},

"breaks": {
  "objectives": [
    "Insert page, column, and section breaks and explain how they differ",
    "Choose the right section break type for a layout change",
    "Reveal breaks with Show/Hide to diagnose layout problems",
    "Replace repeated Enter presses with a proper page break",
  ],
  "opening": {
    "heading": "The difference between a page break and a section break",
    "blocks": [
      {"type": "scenario",
       "role": "You are assembling the annual report at Lakeside Medical Associates.",
       "text": "The report is portrait, but the budget table in the middle needs a landscape page. You set orientation to landscape and every page in the document rotates. You undo, try again, and get the same result.",
       "task": "Learn which break creates an independent region of the document, because orientation applies to sections, not pages."},
      {"type": "paragraph",
       "text": "A page break simply moves the following content to the next page. Everything stays in the same section, so it keeps the same margins, orientation, headers, and page numbering. It is the right tool for starting a new chapter on a fresh page."},
      {"type": "paragraph",
       "text": "A section break creates a genuinely independent region that can have its own orientation, margins, columns, headers, and page numbering. That is why the landscape budget table needs section breaks before and after it: only then can that one region rotate while the rest of the report stays portrait."},
      {"type": "table",
       "caption": "Break types",
       "columns": ["Break", "Effect", "Use for"],
       "rows": [
         ["Page", "Content continues on the next page", "Starting a chapter on a new page"],
         ["Column", "Content continues in the next column", "Controlling where a column ends in a newsletter"],
         ["Section: Next Page", "New section starting on a new page", "A landscape page inside a portrait document"],
         ["Section: Continuous", "New section on the same page", "Changing column count partway down a page"],
         ["Section: Even/Odd Page", "New section on the next even or odd page", "Chapters that must always start on a right-hand page"],
       ]},
      {"type": "callout", "variant": "warning",
       "text": "Never create a page break by pressing Enter repeatedly. Those empty paragraphs stay where they are while the text around them reflows, so adding one sentence earlier in the document pushes your heading to the middle of the next page. Ctrl+Enter inserts a real page break that always starts a new page regardless of what changes above it."},
      {"type": "tip",
       "text": "Turn on Show/Hide (¶ on the Home tab, or Ctrl+Shift+8) to see breaks as labeled dotted lines. When a document's layout is misbehaving in a way you cannot explain, this is the first diagnostic — an unexpected section break is one of the most common causes."},
    ],
  },
  "checks": [{"explanation": "A page break moves subsequent content to the next page while keeping it in the same section, so margins, orientation, and headers are unchanged. Ctrl+Enter inserts one.",
    "rationales": [
      "Correct. A page break starts a new page while leaving the section — and therefore the layout settings — unchanged.",
      "A column break moves content to the top of the next column, which only reaches a new page in the last column of a page.",
      "A continuous section break starts a new section without starting a new page, so it deliberately does not force a page change.",
      "A Next Page section break does start a new page, but it also creates a new section. When you only need a new page, that is more than you want — the extra section can cause header and numbering surprises later.",
    ]}],
},

"columns": {
  "objectives": [
    "Apply a multi-column layout to a whole document or a selection",
    "Control where a column ends with a column break",
    "Choose a column count and width appropriate to the page",
    "Explain why columns are a readability tool",
  ],
  "opening": {
    "heading": "Columns exist to shorten the line",
    "blocks": [
      {"type": "scenario",
       "role": "You are laying out the patient newsletter at Lakeside Medical Associates.",
       "text": "Your first draft runs the text full width across the page. Readers report it feels like hard work, though they cannot say why. The sentences are fine. The lines are simply too long — the eye keeps losing its place travelling back to the start of the next one.",
       "task": "Use columns to bring the line length into the range people read comfortably."},
      {"type": "paragraph",
       "text": "Typographers generally aim for roughly 50 to 75 characters per line. Beyond that, the return sweep from the end of one line to the start of the next becomes unreliable and readers lose their place. On a letter-size page at 11 point, full-width text runs closer to 100 characters, which is why newsletters and magazines are almost always set in columns."},
      {"type": "paragraph",
       "text": "Apply columns from Layout > Columns. Applied with nothing selected, it affects the whole section; with text selected, Word adds continuous section breaks around the selection so only that part becomes multi-column. This is how a newsletter has a full-width masthead above two-column body text."},
      {"type": "tip",
       "text": "A column break (Ctrl+Shift+Enter) pushes the following text to the top of the next column. Use it to stop an article ending with one stranded line, or to make two columns end level at the foot of the page."},
      {"type": "callout", "variant": "info",
       "text": "Two columns suit letter-size portrait pages. Three is workable for short items such as listings but gets tight for body text — narrow columns force awkward hyphenation and ragged spacing. If a three-column layout looks cramped, the answer is usually two columns or a smaller font, not narrower gutters."},
    ],
  },
  "checks": [{"explanation": "A column break forces the following text to the top of the next column. Use it to control where a column ends rather than letting the text break wherever it happens to fall.",
    "rationales": [
      "Returning to a single column is done from Layout > Columns > One, which changes the layout rather than inserting a break.",
      "The line between columns is the 'Line between' option in the Columns dialog, a formatting setting rather than a break.",
      "Correct. The text after the break moves to the top of the next column.",
      "The number of columns is set in the Columns dialog. A column break works within whatever layout is already applied.",
    ]}],
},
}

apply("lib/content/ms-office/word/module5Lessons.ts", M5)
apply("lib/content/ms-office/word/module6Lessons.ts", M6)
