import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from enrich import apply

M2 = {
"text-basics": {
  "objectives": [
    "Select text precisely with the mouse, keyboard, and click shortcuts",
    "Explain the difference between cut, copy, and the clipboard",
    "Use Paste Special to bring in text without importing its formatting",
    "Insert symbols and special characters that are not on the keyboard",
  ],
  "opening": {
    "heading": "Selection is the skill underneath everything else",
    "blocks": [
      {"type": "scenario",
       "role": "You are assembling a patient handout at Lakeside Medical Associates.",
       "text": "A nurse sends you three paragraphs pasted from a manufacturer's website. You drop them into your handout and the text arrives in blue Arial 14 with a grey background, nothing like the rest of your document. You spend eleven minutes manually re-formatting it. There is a keystroke that would have prevented all eleven.",
       "task": "Learn to control what comes along when text moves — and to select exactly the text you mean, the first time."},
      {"type": "paragraph",
       "text": "Every edit in Word begins with a selection. Word applies commands to whatever is selected, so imprecise selection is the root cause of a surprising share of formatting problems — the stray space that gets bolded, the paragraph mark that carries its formatting into the next paragraph. Learning to select with intent removes a whole category of mistakes before it starts."},
      {"type": "table",
       "caption": "Selection shortcuts worth committing to memory",
       "columns": ["To select", "Do this", "Use it when"],
       "rows": [
         ["A word", "Double-click it", "Replacing a single term"],
         ["A sentence", "Ctrl + click anywhere in it", "Rewriting one sentence in a dense paragraph"],
         ["A paragraph", "Triple-click in it", "Restyling or moving a whole block"],
         ["A block of text", "Click at the start, Shift + click at the end", "Any span too long to drag comfortably"],
         ["The whole document", "Ctrl + A", "Applying a font or spacing change everywhere"],
         ["A vertical block", "Hold Alt and drag", "Stripping a column of numbers out of pasted text"],
       ]},
      {"type": "paragraph",
       "text": "The clipboard is the second idea. Cut removes text and holds it; copy duplicates it and holds it; paste places what is held. What most people never learn is that paste has options. Pasting normally brings the source formatting with it, which is why website text arrives looking like a website. Ctrl+Shift+V, or Paste Special > Keep Text Only, brings the words and leaves the formatting behind — and it is the single most useful keystroke in this lesson."},
      {"type": "callout", "variant": "version",
       "text": "In Microsoft 365, Word can be set to default to Keep Text Only for pasted content: File > Options > Advanced > Cut, copy, and paste, and set 'Pasting from other programs' to 'Keep Text Only.' If you paste from the web frequently, changing this once saves the cleanup every time. Office 2019 has the same setting in the same place."},
    ],
  },
  "workedExample": {
    "heading": "Bringing in outside text cleanly",
    "blocks": [
      {"type": "worked-example",
       "title": "Pasting three paragraphs from a website into a formatted handout",
       "task": "Add manufacturer instructions to a patient handout so they match the handout's existing fonts and spacing rather than the website's.",
       "steps": [
         {"move": "Select the source text on the web page and copy it with Ctrl+C.",
          "why": "Standard so far. The problem is not the copy — it is that the clipboard is carrying HTML formatting along with the words, and a normal paste will honor it."},
         {"move": "In Word, place the insertion point where the text belongs, then press Ctrl+Shift+V.",
          "why": "This is Paste Text Only. Word discards the source fonts, colors, and background shading and inserts plain characters, which immediately take on the formatting of the paragraph they land in. The eleven minutes of cleanup never happen."},
         {"move": "If you already pasted normally, press Ctrl+Z and redo it — do not clean up by hand.",
          "why": "Manually stripping formatting almost always leaves something behind: a hidden style, a character-level color, a residual background. Undoing and re-pasting correctly takes two seconds and leaves nothing."},
         {"move": "Turn on Show/Hide (¶) and check what actually arrived.",
          "why": "Pasted web text often carries line breaks where paragraph marks belong, which breaks spacing and list numbering later. Seeing the marks lets you fix the structure now rather than wondering later why a style will not apply correctly."},
       ],
       "result": "Three paragraphs that match the handout exactly, with no residual web formatting and no manual cleanup.",
       "takeaway": "Ctrl+Shift+V is the difference between importing words and importing someone else's design. Make it the default reflex for anything from outside your document."},
    ],
  },
  "checks": [{"explanation": "Ctrl+C copies the selection to the clipboard, leaving the original in place. Its neighbors are worth learning together: Ctrl+X cuts (removes and holds), Ctrl+V pastes, and Ctrl+Z undoes.",
    "rationales": [
      "Ctrl+X is cut — it removes the selected text and holds it on the clipboard rather than leaving it in place.",
      "Ctrl+V pastes whatever is currently on the clipboard. It is the other half of the operation, not the copy itself.",
      "Correct. Ctrl+C copies the selection to the clipboard and leaves the original text untouched.",
      "Ctrl+Z is undo, which reverses your last action. Useful, but unrelated to the clipboard.",
    ]}],
},

"formatting-text": {
  "objectives": [
    "Apply font, size, color, and emphasis deliberately rather than decoratively",
    "Explain why bold, italic, and underline carry different conventional meanings",
    "Use Format Painter to copy formatting from one passage to another",
    "Recognize when direct formatting should be replaced by a style",
  ],
  "opening": {
    "heading": "Formatting is communication, not decoration",
    "blocks": [
      {"type": "scenario",
       "role": "You are producing a discharge instruction sheet at Lakeside Medical Associates.",
       "text": "A patient needs to know two things above all: take the medication with food, and call immediately if a fever passes 101°F. You have written both. They sit in the middle of a wall of identical grey text, and the patient will read neither.",
       "task": "Use formatting to make the most important information impossible to miss — and to make everything else recede."},
      {"type": "paragraph",
       "text": "Emphasis works by contrast, which means it is a budget. If you bold six things on a page, you have bolded nothing — the reader's eye has no landing place. A page with two bold phrases directs attention exactly where you want it. The discipline is not learning what the buttons do; it is restraint about how often you press them."},
      {"type": "paragraph",
       "text": "Conventions matter too, because readers have absorbed them. Bold signals importance and survives scanning. Italic signals a title, a term being defined, or a mild emphasis, and it is harder to read in long runs. Underline, on screen, reads as a hyperlink — underlining ordinary text is the fastest way to make readers click something that is not there. Use bold for emphasis and reserve underline for links."},
      {"type": "table",
       "caption": "What each treatment conventionally means",
       "columns": ["Treatment", "Conventional meaning", "Avoid"],
       "rows": [
         ["Bold", "This is critical; do not skip it", "More than two or three per page"],
         ["Italic", "Title of a work, a defined term, or light emphasis", "Long passages — it slows reading"],
         ["Underline", "A hyperlink", "Ordinary emphasis, on screen especially"],
         ["ALL CAPS", "Short labels and warnings only", "Sentences — capitals remove word shape and slow reading"],
         ["Color", "Category or status, when there is a legend", "Color alone as the only signal — it fails for colorblind readers"],
       ]},
      {"type": "callout", "variant": "warning",
       "text": "Never let color be the only thing carrying meaning. Roughly one in twelve men has some form of color vision deficiency, and a red 'urgent' line that is otherwise identical to the rest of the text is invisible to them. Pair color with bold, an icon, or a word — 'Urgent: call the office' works for everyone."},
      {"type": "tip",
       "text": "Format Painter (the paintbrush on the Home tab) copies formatting rather than text. Click inside text formatted the way you want, click Format Painter, then drag across the target. Double-click the paintbrush to keep it active for multiple targets, and press Esc when you are done."},
    ],
  },
  "checks": [{"explanation": "Italic slants the letterforms. It conventionally marks titles, defined terms, or light emphasis — but it is harder to read in long passages, so keep italic runs short.",
    "rationales": [
      "Bold thickens the strokes to signal importance. It does not slant the letters.",
      "Correct. Italic slants the letterforms, conventionally marking titles, defined terms, or gentle emphasis.",
      "Underline draws a line beneath the text without changing its shape. On screen it reads as a hyperlink, so use it sparingly.",
      "Strikethrough draws a line through the text, marking it as deleted or superseded rather than slanting it.",
    ]}],
},

"find-and-replace": {
  "objectives": [
    "Find text quickly and navigate results with the Navigation pane",
    "Use Replace All safely, and know when to replace one at a time instead",
    "Apply Match case and Find whole words only to avoid unintended matches",
    "Find and replace formatting, not just words",
  ],
  "opening": {
    "heading": "The command that saves an hour and the mistake that costs one",
    "blocks": [
      {"type": "scenario",
       "role": "You maintain practice documents at Lakeside Medical Associates.",
       "text": "The practice's billing contact changes and you must update the name in a forty-page policy manual. You open Replace, type the old surname, type the new one, and click Replace All. Word reports 63 replacements. The name appeared 61 times — the other two were inside the words 'Manning' and 'planning,' which are now nonsense.",
       "task": "Learn the two checkboxes that turn Replace All from a risk into a reliable tool."},
      {"type": "paragraph",
       "text": "Find (Ctrl+F) opens the Navigation pane and lists every match, letting you jump between them. Replace (Ctrl+H) swaps one string for another. The power of Replace All is genuine — it does in one second what would take forty minutes by hand — and so is its danger, because it does exactly what you asked across the entire document, including places you did not think about."},
      {"type": "paragraph",
       "text": "Two options in the More menu prevent nearly every Replace accident. Find whole words only stops 'Ann' from matching inside 'Manning' and 'planning.' Match case stops 'IT' from matching inside 'it,' 'with,' and 'admit.' Together they narrow the search to what you actually meant."},
      {"type": "worked-example",
       "title": "Replacing a name across a long document without breaking words",
       "task": "Change every occurrence of the billing contact's surname in a forty-page manual, without touching words that merely contain those letters.",
       "steps": [
         {"move": "Press Ctrl+H, then click More to expand the options.",
          "why": "The default Replace dialog hides the settings that make it safe. Expanding it first is the habit that prevents the mistake, because the checkboxes are not visible in the collapsed view."},
         {"move": "Check 'Find whole words only' and 'Match case.'",
          "why": "Whole words stops the match from landing inside a longer word. Match case ensures you replace the proper noun and not a lowercase coincidence. These two settings account for the overwhelming majority of Replace All accidents."},
         {"move": "Click Find Next two or three times before replacing anything.",
          "why": "This is the step that separates a careful operator from a hopeful one. Stepping through a few matches shows you what the search is actually catching. If the first three look right, the remaining sixty almost certainly are."},
         {"move": "Click Replace All, then read the count Word reports.",
          "why": "The count is a free verification. If you expected about sixty and Word says sixty-one, that is plausible. If it says two hundred, something matched far more broadly than you intended — press Ctrl+Z immediately, before doing anything else."},
       ],
       "result": "Sixty-one accurate replacements and no corrupted words, verified by a count that matched expectation.",
       "takeaway": "Expand More, restrict the match, spot-check with Find Next, then read the count. Replace All is safe when you have told it precisely what you mean."},
      {"type": "tip",
       "text": "Replace also works on formatting. With the cursor in the Find field, click Format > Font to search for, say, all red text and replace it with black — useful for stripping the editing marks out of a draft that circulated for comment."},
    ],
  },
  "checks": [{"explanation": "Ctrl+H opens Find and Replace with the Replace tab active. Ctrl+F opens Find alone in the Navigation pane, which is what you want when you only need to locate something rather than change it.",
    "rationales": [
      "Ctrl+F opens Find in the Navigation pane. It locates text but offers no way to replace it.",
      "Ctrl+G opens Go To, which jumps to a specific page, section, or bookmark rather than searching for text.",
      "Correct. Ctrl+H opens the dialog with the Replace tab active, ready to swap one string for another.",
      "Ctrl+R right-aligns the current paragraph. It is a formatting shortcut, unrelated to searching.",
    ]}],
},

"lists": {
  "objectives": [
    "Choose between a bulleted and a numbered list based on whether order matters",
    "Build a multilevel list and promote or demote items with Tab and Shift+Tab",
    "Restart or continue numbering when Word guesses wrong",
    "Explain why manually typed numbers cause problems that list formatting avoids",
  ],
  "opening": {
    "heading": "The choice between bullets and numbers is a meaning choice",
    "blocks": [
      {"type": "scenario",
       "role": "You are writing front-desk procedures at Lakeside Medical Associates.",
       "text": "You document the check-in process as a bulleted list. A new hire reads it, verifies insurance before confirming the patient's identity, and discloses coverage details to the wrong person. The steps were all correct. Nothing told the reader they had to happen in order.",
       "task": "Use list type to communicate whether sequence matters — because readers genuinely read it that way."},
      {"type": "paragraph",
       "text": "Numbers mean sequence: do this, then this, then this. Bullets mean membership: these items belong to a set, in no particular order. Readers process that distinction automatically, which is exactly why using the wrong one misleads them. Any procedure where doing step three before step two causes a problem must be numbered."},
      {"type": "paragraph",
       "text": "There is also a mechanical reason to use Word's list formatting rather than typing numbers yourself. A real numbered list renumbers itself when you insert or delete an item. A list of hand-typed numbers does not — insert a step in the middle and you must retype everything below it, and sooner or later a document goes out with two step fours. Let Word own the numbering."},
      {"type": "table",
       "caption": "Which list type to use",
       "columns": ["Content", "List type", "Reason"],
       "rows": [
         ["Check-in procedure", "Numbered", "Order is required; doing them out of sequence causes harm"],
         ["Documents to bring to an appointment", "Bulleted", "All are needed; order is irrelevant"],
         ["Policy manual with sections and subsections", "Multilevel", "Hierarchy is part of the meaning and cross-references depend on it"],
         ["Ranked priorities", "Numbered", "The numbers carry the ranking, not just the sequence"],
       ]},
      {"type": "tip",
       "text": "Inside a list, Tab demotes an item to the next level and Shift+Tab promotes it. This is far faster than the Multilevel List menu, and it works while you are typing, so you never have to break your rhythm to restructure."},
    ],
  },
  "checks": [{"explanation": "Numbers signal sequence, so numbered lists are correct whenever the steps must happen in order. Bullets signal membership in a set, which tells the reader that order does not matter — a genuinely misleading signal on a procedure.",
    "rationales": [
      "Bullets tell the reader the items form a set with no required order, which is precisely the wrong signal for a sequence.",
      "Multilevel lists express hierarchy — sections and subsections. They can be numbered, but the hierarchy is what they are for.",
      "Correct. Numbers communicate sequence, and Word renumbers automatically when you insert or remove a step.",
      "Custom symbols change how a bullet looks. That is decoration; it does not convey order.",
    ]}],
},

"hyperlinks": {
  "objectives": [
    "Insert, edit, and remove hyperlinks, including links to places within the document",
    "Write link text that makes sense to someone reading it out of context",
    "Explain why 'click here' is a problem for screen reader users",
    "Control Word's automatic hyperlink formatting",
  ],
  "opening": {
    "heading": "Link text is read out loud",
    "blocks": [
      {"type": "scenario",
       "role": "You are publishing the patient resources page at Lakeside Medical Associates.",
       "text": "Your document has nine links, and every one says 'click here.' A patient using a screen reader asks it to list the links on the page — a standard way to navigate. The software reads: click here, click here, click here, nine times. The page is unusable, and nothing about it looks wrong on screen.",
       "task": "Write link text that says where the link goes, so the document works for everyone reading it."},
      {"type": "paragraph",
       "text": "Screen readers can extract a list of every link in a document, and many people navigate that way rather than reading linearly. That means link text has to make sense standing alone. 'Click here' conveys nothing out of context. 'Download the new patient intake form' conveys everything, and it reads better on screen too."},
      {"type": "paragraph",
       "text": "The rule is simple: put the destination in the link text itself. Instead of 'For directions, click here,' write 'See directions to our Lakeside office.' Instead of 'Our hours are listed here,' write 'View our current office hours.' The sentence gets shorter and the document gets more accessible at the same time."},
      {"type": "callout", "variant": "warning",
       "text": "Printed documents cannot be clicked. If a document will be printed as well as read on screen, write the destination so it survives on paper — 'visit lakesidemedical.example/forms' — or add the address in parentheses after a descriptive link. A printed page full of blue underlined 'click here' is a dead end."},
      {"type": "tip",
       "text": "Ctrl+K inserts or edits a hyperlink on the selected text. In the same dialog, the ScreenTip button sets the tooltip that appears on hover, which is a good place for a note like 'opens in a new window' or 'PDF, 400 KB.'"},
    ],
  },
  "checks": [{"explanation": "In the Word desktop app, links are Ctrl+click by default so that a normal click can place your cursor for editing without launching a browser. In Word Online and in Reading view, a plain click follows the link.",
    "rationales": [
      "Double-clicking selects the word under the cursor. It edits the link text rather than following the link.",
      "Correct. Ctrl+click follows the link, while a plain click places the insertion point so you can edit the text.",
      "Right-click does offer Open Hyperlink on its menu, so this works — but it is three actions where Ctrl+click is one, and it is not the standard method.",
      "Pressing Enter with a link selected replaces the selected text with a new paragraph. That deletes the link rather than following it.",
    ]}],
},

"printing-documents": {
  "objectives": [
    "Preview a document accurately before committing it to paper",
    "Print a specific page range, selection, or set of pages",
    "Choose duplex, collation, and scaling settings appropriately",
    "Diagnose the common causes of a document that prints differently than it appears",
  ],
  "opening": {
    "heading": "Print preview is a proofreading tool",
    "blocks": [
      {"type": "scenario",
       "role": "You are preparing packets for tomorrow's new-patient orientation at Lakeside Medical Associates.",
       "text": "You send forty copies of a six-page packet to the printer. Two hundred and forty sheets later, you discover a seventh page containing one orphaned line — 'Thank you for choosing Lakeside.' Forty extra sheets, forty stapling errors, and a recycling bin full of paper.",
       "task": "Use the print pane to catch layout problems before they become physical objects."},
      {"type": "paragraph",
       "text": "The print pane in Backstage view shows the document as the printer will produce it, including margins the screen view can hide. Check the page count first — a document that shows six pages on screen and seven in preview has an orphaned line, a stray page break, or an empty paragraph at the end. Deleting that is thirty seconds of work that saves forty sheets."},
      {"type": "table",
       "caption": "Print settings worth understanding before a large job",
       "columns": ["Setting", "What it does", "When it matters"],
       "rows": [
         ["Print Range", "Prints specific pages, e.g. 1-3, 7", "Reprinting one corrected page instead of the whole packet"],
         ["Print Selection", "Prints only the highlighted text", "Pulling one section out of a long document"],
         ["Collated", "Produces complete sets in order", "Any multi-page document you will hand out as packets"],
         ["Print on Both Sides", "Duplex printing", "Halves the paper for anything over two pages"],
         ["Scale to Paper Size", "Fits the layout to the loaded paper", "A document laid out for Letter printing on A4, or the reverse"],
       ]},
      {"type": "tip",
       "text": "If a document prints with different line breaks than it shows on screen, the usual cause is a font the printer does not have, or a printer driver substituting one. Exporting to PDF and printing that instead embeds the fonts and guarantees the output matches what you designed."},
    ],
  },
  "checks": [{"explanation": "File > Print opens Backstage view with a live preview beside the settings, so you can check pagination and margins and adjust settings in the same place before committing to paper.",
    "rationales": [
      "The View tab changes how you see the document while editing — Read Mode, zoom, multiple pages. It is not the print preview.",
      "The Home tab holds text formatting commands. Nothing there previews printed output.",
      "Correct. File > Print shows a live preview next to the print settings, so you can catch and fix problems before printing.",
      "The Page Layout dialog sets margins, orientation, and paper size. It changes the layout but does not preview the printed result.",
    ]}],
},
}

M3 = {
"pictures-text-wrapping": {
  "objectives": [
    "Insert images from your computer and from online sources",
    "Choose a text wrapping mode that matches how the image relates to the text",
    "Explain the difference between In Line with Text and the floating wrap modes",
    "Anchor an image so it stays with the content it illustrates",
  ],
  "opening": {
    "heading": "Wrapping decides whether an image behaves like a letter or like a sticker",
    "blocks": [
      {"type": "scenario",
       "role": "You are laying out a wellness newsletter at Lakeside Medical Associates.",
       "text": "You place a photo beside a paragraph about flu season. You add two sentences higher up the page and the photo leaps to page three, landing beside an unrelated article about parking. You drag it back. You add another sentence. It jumps again.",
       "task": "Understand anchoring and wrapping well enough that images stay where you put them."},
      {"type": "paragraph",
       "text": "There are really only two behaviors, and everything else is a variation. In Line with Text treats the image as an enormous character — it sits in the line, moves when text moves, and cannot have text beside it. Every other mode makes the image floating: it sits in its own layer, text flows around it according to the mode you choose, and it is tied to a paragraph by an anchor."},
      {"type": "paragraph",
       "text": "The anchor is the part almost nobody is taught, and it explains the jumping. A floating image is attached to a specific paragraph; when that paragraph moves to another page, the image follows. Turn on the anchor symbol display and you can see which paragraph owns the image — and drag the anchor to a different paragraph if it is attached to the wrong one."},
      {"type": "table",
       "caption": "Wrap modes and what they are for",
       "columns": ["Mode", "Behavior", "Use for"],
       "rows": [
         ["In Line with Text", "Sits in the text line like a character", "Icons, signatures, anything in a table cell"],
         ["Square", "Text flows around the bounding box", "A photo beside a paragraph — the common newsletter case"],
         ["Tight", "Text follows the image's actual shape", "Cut-out images with transparent backgrounds"],
         ["Top and Bottom", "Text stops above and resumes below", "A wide figure that should own its horizontal band"],
         ["Behind Text", "Image sits under the text", "Watermarks and background graphics"],
         ["In Front of Text", "Image covers the text", "Callout arrows and annotations over a screenshot"],
       ]},
      {"type": "tip",
       "text": "If an image will not stop moving, select it, open Layout Options, and choose 'Fix position on page.' The image stays put on that page regardless of text edits. Use it sparingly — it is right for a masthead and wrong for a figure that must stay next to its caption."},
    ],
  },
  "checks": [{"explanation": "In Line with Text places the image inside the text flow itself, as though it were a very large character. This is why text cannot appear beside it — the image occupies the whole line. Every other mode makes the image float in its own layer.",
    "rationales": [
      "Correct. The image sits in the line like a character, moving with the text and preventing text from appearing beside it.",
      "Square floats the image and flows text around its rectangular bounding box, which places text beside it rather than on the same line.",
      "Tight floats the image and flows text around its actual contours, so it also places text alongside rather than in line.",
      "Behind Text floats the image on a lower layer, with text running over the top of it.",
    ]}],
},

"formatting-pictures": {
  "objectives": [
    "Crop an image to improve its composition, and crop to a shape",
    "Adjust brightness, contrast, and color to make an image usable",
    "Compress images to keep file size manageable",
    "Judge when a picture style helps and when it distracts",
  ],
  "opening": {
    "heading": "Cropping is editing, not trimming",
    "blocks": [
      {"type": "scenario",
       "role": "You are building a staff directory at Lakeside Medical Associates.",
       "text": "Eleven staff photos arrive from eleven different phones. Some are portrait, some landscape, some show the whole waiting room with a person somewhere in it. Dropped into the directory as-is, they make the page look like a scrapbook. The document is going to new patients.",
       "task": "Crop and adjust the photos so they read as one consistent set."},
      {"type": "paragraph",
       "text": "Cropping serves composition, not just size. Cropping every headshot to the same aspect ratio and framing each face in roughly the same position makes eleven unrelated photos read as one deliberate set. Resizing alone cannot do that — a wide photo scaled down is still a wide photo of a waiting room."},
      {"type": "paragraph",
       "text": "Compression is the practical companion. A modern phone photo can be several megabytes; eleven of them produce a document too large to email. Picture Format > Compress Pictures reduces resolution to what the output actually needs. Use 220 ppi for something that will be printed, 150 ppi for on-screen reading, and 96 ppi for email. Always uncheck 'Apply only to this picture' when you want the whole document reduced."},
      {"type": "callout", "variant": "warning",
       "text": "Cropping hides the cropped-away area; it does not delete it by default. Anyone who receives the file can drag the crop handles back out and reveal what you removed. If you cropped to hide something — another patient in the background, a name badge, a screen with data on it — you must also run Compress Pictures with 'Delete cropped areas of pictures' checked. Otherwise you have concealed it visually while still shipping the pixels."},
      {"type": "tip",
       "text": "Crop to Shape (Crop dropdown > Crop to Shape) trims the image to a circle or rounded rectangle in one step. Circular headshots are a quick, reliable way to make photos of mixed quality look coordinated."},
    ],
  },
  "checks": [{"explanation": "Crop trims away the outer parts of an image so you keep only the region you want. Note that by default Word hides rather than discards the cropped area — use Compress Pictures with 'Delete cropped areas' to remove it for good.",
    "rationales": [
      "Corrections adjusts sharpness, brightness, and contrast. It changes how the existing image looks, not how much of it is visible.",
      "Artistic Effects applies stylized filters such as pencil sketch or blur. It restyles the whole image rather than trimming it.",
      "Correct. Crop removes the outer edges of the image, letting you keep only the part you want to show.",
      "Picture Styles apply frames, shadows, and borders around the image. They decorate the edge rather than remove it.",
    ]}],
},

"shapes": {
  "objectives": [
    "Insert and resize shapes, and constrain proportions while drawing",
    "Add and format text inside a shape",
    "Apply fills, outlines, and effects consistently across several shapes",
    "Understand stacking order and how it affects what is visible",
  ],
  "opening": {
    "heading": "Shapes are for showing relationships",
    "blocks": [
      {"type": "scenario",
       "role": "You are documenting the referral process at Lakeside Medical Associates.",
       "text": "The referral workflow has six steps and two decision points. Written as a paragraph, it takes four readings to follow. Drawn as six boxes with arrows and two diamonds, it takes about eight seconds — and new staff stop asking which form goes where.",
       "task": "Use shapes to make a process visible instead of describing it."},
      {"type": "paragraph",
       "text": "A diagram earns its place when the relationship between things is the point. A sequence, a hierarchy, a decision with branches — these are genuinely hard to hold in your head from prose and immediately obvious as a drawing. A shape added because the page looked plain earns nothing and costs the reader attention."},
      {"type": "paragraph",
       "text": "Text goes directly inside a shape: click the shape and start typing. There is no need to lay a separate text box over it, and doing so creates two objects that must be moved together and inevitably drift apart. Text typed inside the shape moves with it, wraps within it, and stays centered automatically."},
      {"type": "table",
       "caption": "Conventional shape meanings in a process diagram",
       "columns": ["Shape", "Means", "Example"],
       "rows": [
         ["Rectangle", "A step or action", "Verify insurance eligibility"],
         ["Diamond", "A decision with branches", "Referral requires prior authorization?"],
         ["Rounded rectangle / oval", "Start or end point", "Referral received"],
         ["Arrow", "Flow from one step to the next", "Connects each step in order"],
         ["Parallelogram", "Input or output — a document or form", "Completed referral form"],
       ]},
      {"type": "tip",
       "text": "Hold Shift while drawing to constrain proportions — a perfect circle from the oval tool, a true square from the rectangle, or a straight line locked to 15-degree increments. Hold Ctrl while dragging an existing shape to duplicate it, which is the fastest way to build six identical process boxes."},
    ],
  },
  "checks": [{"explanation": "Shapes accept text directly — select the shape and type. The text becomes part of the shape, so it moves, resizes, and rotates with it. Overlaying a separate text box creates two objects that will eventually separate.",
    "rationales": [
      "This works visually but creates two independent objects. Move the shape and the text box stays behind, which is why the approach falls apart in any document that gets edited.",
      "Correct. Click the shape and type — the text belongs to the shape and travels with it.",
      "That command inserts a standalone text box, which is a different object. It is the right tool for free-floating text, not for labeling a shape.",
      "Right-clicking a shape does offer Add Text on the context menu, but it opens no dialog — and simply clicking and typing achieves the same thing in one step.",
    ]}],
},

"text-boxes": {
  "objectives": [
    "Insert built-in and custom text boxes and position them precisely",
    "Format text box fills, borders, and internal margins",
    "Explain when a text box is the right tool and when a table or paragraph is better",
    "Keep text boxes accessible for screen reader users",
  ],
  "opening": {
    "heading": "A text box breaks text out of the flow",
    "blocks": [
      {"type": "scenario",
       "role": "You are designing a patient information sheet at Lakeside Medical Associates.",
       "text": "The sheet needs a bordered box in the margin holding the after-hours number, visible no matter which paragraph a patient is reading. Ordinary paragraphs cannot do that — they sit in the flow and move as text is added above them.",
       "task": "Use a text box to place content precisely, and know when not to reach for one."},
      {"type": "paragraph",
       "text": "A text box is a container that floats independently of the main text flow, so you can put words anywhere on the page — in a margin, over an image, in a sidebar. That independence is the whole point, and also the reason to be careful with it."},
      {"type": "callout", "variant": "warning",
       "text": "Screen readers may read text boxes out of order, or skip them entirely, because they sit outside the main document flow. Never put essential information only in a text box. If the after-hours number matters, it also belongs in the body text — the box is emphasis, not the sole delivery mechanism. Run Review > Check Accessibility before distributing any document that uses text boxes heavily."},
      {"type": "table",
       "columns": ["You want", "Use", "Why"],
       "rows": [
         ["A pull quote or sidebar", "Text box", "Needs to sit outside the flow, in a fixed place"],
         ["Aligned rows and columns of data", "Table", "Tables handle alignment and stay accessible"],
         ["An indented block quotation", "Paragraph with indents", "Stays in the flow and in the reading order"],
         ["A label over a screenshot", "Text box, In Front of Text", "Must sit on top of an image at an exact spot"],
       ]},
      {"type": "tip",
       "text": "Right-click a text box and choose Format Shape > Text Options > Text Box to set internal margins. The default padding is often too tight when you add a border — a little breathing room between the border and the text is most of what makes a box look professional rather than cramped."},
    ],
  },
  "checks": [{"explanation": "A text box floats independently of the main text flow, so you can position words anywhere on the page — a margin, a sidebar, or on top of an image. That independence is exactly why screen readers may miss it, so never let a text box be the only place important information appears.",
    "rationales": [
      "Tables organize content into rows and columns within the text flow. That is a different tool with different behavior.",
      "Paragraph borders (Home > Borders) put a box around a paragraph while it stays in the flow. Useful, but it cannot be positioned freely.",
      "Correct. A text box floats independently of the text flow, so it can be placed anywhere on the page.",
      "Hyperlinks are created with Ctrl+K on selected text. A text box is a container, not a linking tool.",
    ]}],
},

"align-order-group": {
  "objectives": [
    "Align and distribute multiple objects precisely instead of by eye",
    "Control stacking order with Bring Forward and Send Backward",
    "Use the Selection pane to find and select objects that are hidden behind others",
    "Group objects so they move and scale as a unit",
  ],
  "opening": {
    "heading": "Aligning by eye is why layouts look almost right",
    "blocks": [
      {"type": "scenario",
       "role": "You are finishing the referral workflow diagram at Lakeside Medical Associates.",
       "text": "Six process boxes, positioned by dragging. On screen at 100% they look fine. Printed and pinned by the front desk, three of them are visibly two millimetres out of line, and the diagram reads as sloppy — which is what people then assume about the process it describes.",
       "task": "Use the alignment tools so the layout is actually correct rather than approximately correct."},
      {"type": "paragraph",
       "text": "Human eyes are good at detecting misalignment and bad at preventing it. Select several objects, then Shape Format > Align > Align Left, and Word puts every left edge on precisely the same coordinate. Align > Distribute Horizontally makes the gaps between them mathematically equal. Both take one click and are exact in a way dragging never is."},
      {"type": "paragraph",
       "text": "Grouping is the follow-up. Once a diagram is aligned, select every piece and press Ctrl+G to group them into a single object. From then on, moving or resizing the group preserves every internal relationship. Without grouping, moving a six-box diagram means moving six objects and re-aligning them at the destination."},
      {"type": "tip",
       "text": "The Selection pane (Home > Select > Selection Pane, or Alt+F10) lists every object on the page. It is the only practical way to select something completely hidden behind another object, and you can rename entries — 'Step 3 box' rather than 'Rectangle 47' — which makes a complex diagram far easier to maintain."},
      {"type": "worked-example",
       "title": "Turning six dragged boxes into a clean diagram",
       "task": "Take six roughly positioned process boxes and make them exactly aligned, evenly spaced, and movable as one object.",
       "steps": [
         {"move": "Click the first box, then Shift+click the other five.",
          "why": "Shift+click adds to a selection rather than replacing it. Every alignment command works on the current selection, so getting all six selected is the prerequisite for everything that follows."},
         {"move": "Shape Format > Align > Align Left.",
          "why": "Word moves every selected object so its left edge sits at the leftmost edge in the selection. This is exact to the pixel, which is the difference between a diagram that looks intentional and one that looks hand-placed."},
         {"move": "Shape Format > Align > Distribute Vertically.",
          "why": "This equalizes the vertical gaps between all six. Distribution needs at least three objects to be meaningful, and it fixes the uneven spacing that dragging always produces."},
         {"move": "With all six still selected, press Ctrl+G to group.",
          "why": "The diagram becomes one object. It can now be moved, resized, or wrapped as a unit without any internal drift. Ctrl+Shift+G ungroups again when you need to edit an individual box."},
       ],
       "result": "A precisely aligned, evenly distributed diagram that behaves as a single object.",
       "takeaway": "Align, distribute, then group. Three commands convert an approximate layout into an exact one, and stop it from degrading the next time someone edits the page."},
    ],
  },
  "checks": [{"explanation": "Grouping combines several objects into one, so moving, resizing, or rotating the group applies to everything inside it and preserves the relationships between the pieces. Ctrl+Shift+G ungroups them again.",
    "rationales": [
      "Grouping does not lock anything — the group moves freely. You are thinking of 'Fix position on page,' which is a layout option rather than grouping.",
      "Grouping leaves every object's fill exactly as it was. It changes how they are selected and moved, not how they look.",
      "Grouping applies no formatting at all. To style several objects identically, select them all and apply the style, which is a separate operation.",
      "Correct. The objects behave as a single unit, so the diagram keeps its internal alignment wherever you move it.",
    ]}],
},
}

M4 = {
"headers-and-footers": {
  "objectives": [
    "Add headers and footers, including automatic page numbers and dates",
    "Use a different first page so a letterhead does not repeat",
    "Explain how section breaks let headers differ between parts of a document",
    "Choose between a date that updates automatically and one that stays fixed",
  ],
  "opening": {
    "heading": "Headers are how a page proves where it came from",
    "blocks": [
      {"type": "scenario",
       "role": "You prepare clinical documentation packets at Lakeside Medical Associates.",
       "text": "A twelve-page packet goes to a specialist. It is unstapled at the other end, mixed with pages from two other practices, and reassembled. Half the pages carry no identification and no page numbers. Nobody can tell which pages belong together, or whether any are missing.",
       "task": "Put identifying information on every page automatically, so a loose sheet is never anonymous."},
      {"type": "paragraph",
       "text": "A header or footer is defined once and repeats on every page — the practice name, the document title, and 'Page X of Y' so a reader can tell at a glance that page 7 of 12 is missing. Typing that on each page by hand is not just slow; it breaks the moment the document repaginates."},
      {"type": "paragraph",
       "text": "The date field has a subtlety worth getting right. Insert > Date & Time offers an 'Update automatically' checkbox. Checked, the date rewrites itself to today every time the document opens — correct for a template, and actively wrong for a letter, because reopening a letter from March in September silently changes its date. For anything with a fixed issuance date, leave that box unchecked."},
      {"type": "callout", "variant": "warning",
       "text": "Different First Page (on the Header & Footer contextual tab) stops the header appearing on page one, which is what you want when page one carries a full letterhead. For headers that differ between parts of a longer document, you need section breaks — and you must also turn off 'Link to Previous' in the new section, or Word keeps inheriting the previous section's header and the change appears to do nothing."},
    ],
  },
  "checks": [{"explanation": "A header is content defined once in the top margin that Word repeats on every page — practice name, document title, page numbers. That repetition is the point: it identifies a page that has been separated from the rest of its document.",
    "rationales": [
      "Page borders are set under Design > Page Borders. That is decoration around the page edge, unrelated to headers.",
      "Fonts and colors come from the document theme under the Design tab. A header holds content, not theme settings.",
      "Correct. Content placed in the header repeats automatically at the top of every page.",
      "A table of contents is inserted from References > Table of Contents and appears in the body of the document, not in the header.",
    ]}],
},

"track-changes": {
  "objectives": [
    "Turn Track Changes on and recognize how edits are displayed",
    "Switch between markup views and explain what each one hides",
    "Accept and reject changes individually or in bulk",
    "Remove all tracked changes and comments before sending a document externally",
  ],
  "opening": {
    "heading": "The markup you cannot see is still in the file",
    "blocks": [
      {"type": "scenario",
       "role": "You are finalizing a policy document at Lakeside Medical Associates.",
       "text": "The draft went through three reviewers. You switch the display to 'No Markup,' the document looks clean, and you email it to the practice's insurer. The insurer opens it, switches to All Markup, and reads every deleted sentence, including a reviewer's comment questioning whether a colleague is competent to sign off on the policy.",
       "task": "Understand that display mode hides markup from you, not from anyone else — and learn the step that actually removes it."},
      {"type": "paragraph",
       "text": "This is the single most consequential misunderstanding in Word. Simple Markup and No Markup change what you see on screen. They do not alter the file. Every deletion, insertion, and comment remains stored in the document and is one dropdown away for whoever opens it next."},
      {"type": "paragraph",
       "text": "To actually remove tracked changes you must resolve them: Review > Accept > Accept All Changes, and Review > Delete > Delete All Comments in Document. Then verify with File > Info > Check for Issues > Inspect Document, which reports any remaining revisions, comments, or hidden metadata."},
      {"type": "table",
       "caption": "What each display mode shows",
       "columns": ["Mode", "You see", "The file contains"],
       "rows": [
         ["Simple Markup", "Clean text with change bars in the margin", "All tracked changes"],
         ["All Markup", "Every insertion, deletion, and comment", "All tracked changes"],
         ["No Markup", "The document as if all changes were accepted", "All tracked changes — nothing has been removed"],
         ["Original", "The document before any edits", "All tracked changes"],
       ]},
      {"type": "worked-example",
       "title": "Clearing a reviewed document before it leaves the practice",
       "task": "Take a policy draft with three rounds of tracked edits and comments and produce a file that genuinely contains none of them.",
       "steps": [
         {"move": "Switch to All Markup and read the document through.",
          "why": "You cannot make good accept-or-reject decisions on changes you have not seen. All Markup is the only view that shows everything, and reading it once is how you catch a reviewer's change you actually disagree with."},
         {"move": "Review > Accept > Accept All Changes, or step through with Accept and Reject individually.",
          "why": "Accepting is what physically applies each edit and removes the revision record. Bulk-accept when you have already reviewed and agree with everything; step through individually when the edits are contested."},
         {"move": "Review > Delete > Delete All Comments in Document.",
          "why": "Comments are stored separately from tracked changes, so accepting all changes leaves every comment intact. This is the step people skip, and comments are usually the more embarrassing of the two."},
         {"move": "File > Info > Check for Issues > Inspect Document, then remove what it finds.",
          "why": "The Document Inspector reports tracked changes, comments, hidden text, and author metadata that the Review tab does not surface. It is the only reliable verification, and it takes about fifteen seconds."},
         {"move": "Turn Track Changes off before saving.",
          "why": "If it is still on, your own final cleanup edits become a new round of tracked changes — and you ship the problem you just spent five minutes fixing."},
       ],
       "result": "A file that contains no revisions, no comments, and no reviewer metadata — verified, not assumed.",
       "takeaway": "Changing the view hides markup from you alone. Accept, delete comments, inspect, and turn tracking off — anything less ships the edit history with the document."},
    ],
  },
  "checks": [{"explanation": "Track Changes records every insertion, deletion, and formatting change with an attribution to the person who made it, so a reviewer can see exactly what was altered and accept or reject each edit individually.",
    "rationales": [
      "That describes AutoCorrect, which fixes typing as you go. Track Changes records edits; it does not make them for you.",
      "Correct. Word marks each insertion, deletion, and formatting change and attributes it to its author, so every edit can be reviewed individually.",
      "That describes version history, which OneDrive and SharePoint provide separately. Track Changes marks up edits within a single file.",
      "That describes Restrict Editing under the Review tab. Track Changes records edits rather than preventing them — though you can lock tracking on so reviewers cannot turn it off.",
    ]}],
},

"comments": {
  "objectives": [
    "Insert, reply to, resolve, and delete comments",
    "Explain the difference between resolving and deleting a comment",
    "Navigate between comments efficiently during a review",
    "Write comments that a colleague can act on without asking a follow-up question",
  ],
  "opening": {
    "heading": "Comments are a conversation with a future reader",
    "blocks": [
      {"type": "scenario",
       "role": "You are reviewing a colleague's intake form revision at Lakeside Medical Associates.",
       "text": "You leave a comment that says 'This is confusing.' Your colleague opens it three days later, reads the paragraph five times, cannot work out which part you meant or what would fix it, and either guesses or comes to find you. Either way the comment cost more time than it saved.",
       "task": "Write comments specific enough to act on, and manage the review so nothing is silently lost."},
      {"type": "paragraph",
       "text": "A comment attaches a note to a specific selection without altering the text. That specificity is its value — select the exact phrase you mean, not the whole paragraph, so the reader knows precisely what you are pointing at."},
      {"type": "paragraph",
       "text": "Say what is wrong and what would resolve it. 'This is confusing' gives the author nothing. 'Does \"within 24 hours\" mean business hours or calendar hours? Suggest stating it explicitly' names the ambiguity and proposes the fix, and it can be actioned in thirty seconds without a conversation."},
      {"type": "callout", "variant": "info",
       "text": "Resolving and deleting are different. A resolved comment greys out and stays in the document, preserving the record of what was raised and that it was addressed. A deleted comment is gone. During an active review, resolve rather than delete — the thread is the evidence of why the document says what it says. Delete everything only in the final cleanup before the document leaves the practice."},
      {"type": "tip",
       "text": "Ctrl+Alt+M inserts a comment on the current selection. Review > Previous and Next step through comments in order, which is the reliable way to make sure none is missed in a long document — scrolling and looking is not."},
    ],
  },
  "checks": [{"explanation": "Resolving greys the comment out to show it has been dealt with, while keeping it in the document as a record of what was raised and settled. Deleting removes it entirely, along with that history.",
    "rationales": [
      "That describes deleting. Resolving deliberately keeps the comment so the review history survives.",
      "Comments and footnotes are unrelated features. Resolving never converts one into the other.",
      "Correct. The comment greys out to show it is addressed but remains visible as a record of the discussion.",
      "Resolving a comment changes nothing in the document text. Comments annotate; they never edit.",
    ]}],
},
}

apply("lib/content/ms-office/word/module2Lessons.ts", M2)
apply("lib/content/ms-office/word/module3Lessons.ts", M3)
apply("lib/content/ms-office/word/module4Lessons.ts", M4)
